type Lang = string;

interface GameMeta { title:string; bg:string; icon:string; img?:string; desc:string; sub?:string }
interface Bullet { label:string; text:string }
interface GameInfoSection { heading:string; icon:string; body?:string; bullets?:Bullet[] }

const BGSMAP: Record<string,{bg:string;icon:string;img?:string}> = {
  dice:      { bg:"linear-gradient(135deg,#0f2a6e,#1a5cd6)",  icon:"🎲", img:"/dice-card.jpg" },
  plinko:    { bg:"linear-gradient(135deg,#6e0a14,#d6293e)",  icon:"🎯", img:"/plinko-thumb.jpg" },
  keno:      { bg:"linear-gradient(135deg,#7a4200,#f4a91f)",  icon:"🔮", img:"/keno-thumb.jpg" },
  blackjack: { bg:"linear-gradient(135deg,#5c2800,#d67a10)",  icon:"🃏", img:"/blackjack-thumb.jpg" },
  mines:     { bg:"linear-gradient(135deg,#0a1e3a,#1a4d8a)",  icon:"💎", img:"/mines-card.jpg" },
  slot:      { bg:"linear-gradient(135deg,#5a0a7a,#c020d0)",  icon:"🍬" },
  hilo:      { bg:"linear-gradient(135deg,#004a2a,#00a85a)",  icon:"🃠", img:"/hilo-card.jpg" },
  roulette:  { bg:"linear-gradient(135deg,#1a0a2e,#4a1a7a)",  icon:"🎡", img:"/roulette-card.jpg" },
  baccarat:  { bg:"linear-gradient(135deg,#001830,#003a7a)",  icon:"🃠", img:"/baccarat-card.jpg" },
};

type GameKey = "dice"|"plinko"|"keno"|"blackjack"|"mines"|"slot"|"hilo"|"roulette"|"baccarat";

const META_TRANS: Record<string, Record<GameKey,{desc:string;sub?:string;title?:string}>> = {
  es: {
    dice:      { title:"Mander Dados",     desc:"Lanza los dados y apuesta si el resultado cae por encima o por debajo de tu número objetivo. Tú controlas la probabilidad de ganar y el pago — cuanto mayor el riesgo, mayor la recompensa." },
    plinko:    { title:"Mander Plinko",    desc:"Suelta una bola desde la cima de una pirámide de clavos y observa cómo rebota hasta caer en un slot multiplicador. Elige tu nivel de riesgo y el número de filas para controlar la distribución del pago." },
    keno:      { title:"Mander Keno",      desc:"Elige hasta 10 números de un tablero de 40 casillas y observa cuántos coinciden con los 10 resultados sorteados. Selecciona tu nivel de riesgo para controlar la tabla de pagos." },
    blackjack: { title:"Mander Blackjack", desc:"Juega al Blackjack clásico con un zapato de 6 barajas verificado criptográficamente. Cada mano se reparte con tecnología provably fair. Pide, plántate, dobla o divide hasta llegar a 21." },
    mines:     { title:"Mander Mines",     desc:"Navega por un campo minado descubriendo gemas y multiplicando tu apuesta. Elige el tamaño de la cuadrícula y la cantidad de minas, luego revela casillas una a una. Cobra cuando quieras." },
    slot:      { title:"Candy Burst",      desc:"Gira los carretes y combina símbolos de dulces para ganar premios. Bonificaciones especiales, multiplicadores y giros gratis te esperan en cada tirada.", sub:"Slots" },
    hilo:      { title:"Mander Hilo",      desc:"Predice si la siguiente carta será mayor o menor que la carta actual. Encadena aciertos para multiplicar tu apuesta o retira tus ganancias en cualquier momento." },
    roulette:  { title:"Mander Ruleta",    desc:"Ruleta Europea con 37 números (0-36). Coloca fichas en números individuales, columnas, docenas o apuestas externas. Haz girar la rueda y descubre dónde cae la bola." },
    baccarat:  { title:"Mander Baccarat",  desc:"El clásico juego de cartas donde apostás al Jugador, la Banca o un Empate. Las cartas se reparten con totales módulo 10 y se aplican las reglas de tercera carta estándar." },
  },
  en: {
    dice:      { title:"Mander Dice",      desc:"Roll the dice and bet whether the result lands above or below your target number. You control the win probability and payout — the greater the risk, the greater the reward." },
    plinko:    { title:"Mander Plinko",    desc:"Drop a ball from the top of a peg pyramid and watch it bounce into a multiplier slot. Choose your risk level and row count to control the payout distribution." },
    keno:      { title:"Mander Keno",      desc:"Pick up to 10 numbers from a 40-tile board and see how many match the 10 drawn results. Select your risk level to control the payout table." },
    blackjack: { title:"Mander Blackjack", desc:"Play classic Blackjack with a cryptographically verified 6-deck shoe. Every hand is dealt with provably fair technology. Hit, stand, double, or split to reach 21." },
    mines:     { title:"Mander Mines",     desc:"Navigate a minefield uncovering gems and multiplying your bet. Choose the grid size and mine count, then reveal tiles one by one. Cash out whenever you want." },
    slot:      { title:"Candy Burst",      desc:"Spin the reels and match candy symbols to win prizes. Special bonuses, multipliers, and free spins await on every spin. Luck is on your side!", sub:"Slots" },
    hilo:      { title:"Mander Hi-Lo",     desc:"Predict whether the next card will be higher or lower than the current one. Chain correct guesses to multiply your bet or withdraw your winnings at any time." },
    roulette:  { title:"Mander Roulette",  desc:"European Roulette with 37 numbers (0-36). Place chips on single numbers, columns, dozens, or outside bets. Spin the wheel and discover where the ball lands." },
    baccarat:  { title:"Mander Baccarat",  desc:"The classic card game where you bet on the Player, Banker, or Tie. Cards are dealt with modulo-10 totals and standard third-card rules apply." },
  },
  pt: {
    dice:      { title:"Mander Dados",     desc:"Lance os dados e aposte se o resultado cai acima ou abaixo do seu número alvo. Você controla a probabilidade de vitória e o pagamento — quanto maior o risco, maior a recompensa." },
    plinko:    { title:"Mander Plinko",    desc:"Solte uma bola do topo de uma pirâmide de pinos e veja como ela quica até cair em um slot multiplicador. Escolha seu nível de risco e o número de linhas." },
    keno:      { title:"Mander Keno",      desc:"Escolha até 10 números de um tabuleiro de 40 casas e veja quantos coincidem com os 10 resultados sorteados. Selecione seu nível de risco para controlar a tabela de pagamentos." },
    blackjack: { title:"Mander Blackjack", desc:"Jogue Blackjack clássico com um sapato de 6 baralhos verificado criptograficamente. Cada mão é distribuída com tecnologia provably fair. Peça, pare, dobre ou divida." },
    mines:     { title:"Mander Mines",     desc:"Navegue por um campo minado descobrindo gemas e multiplicando sua aposta. Escolha o tamanho da grade e a quantidade de minas, depois revele casas uma a uma." },
    slot:      { title:"Candy Burst",      desc:"Gire os rolos e combine símbolos de doces para ganhar prêmios. Bônus especiais, multiplicadores e giros grátis aguardam em cada rodada.", sub:"Slots" },
    hilo:      { title:"Mander Hilo",      desc:"Preveja se a próxima carta será maior ou menor que a atual. Encadeie acertos para multiplicar sua aposta ou retire seus ganhos a qualquer momento." },
    roulette:  { title:"Mander Roleta",    desc:"Roleta Europeia com 37 números (0-36). Coloque fichas em números individuais, colunas, dúzias ou apostas externas. Gire a roda e descubra onde a bola cai." },
    baccarat:  { title:"Mander Baccarat",  desc:"O clássico jogo de cartas onde você aposta no Jogador, no Banco ou no Empate. As cartas são distribuídas com totais módulo 10 e as regras padrão de terceira carta se aplicam." },
  },
  de: {
    dice:      { title:"Mander Würfel",    desc:"Wirf die Würfel und wette, ob das Ergebnis über oder unter deiner Zielzahl liegt. Du kontrollierst die Gewinnwahrscheinlichkeit und die Auszahlung — je höher das Risiko, desto höher die Belohnung." },
    plinko:    { title:"Mander Plinko",    desc:"Lasse eine Kugel von oben einer Stiftpyramide fallen und beobachte, wie sie in einen Multiplikator-Slot hüpft. Wähle dein Risikolevel und die Reihenzahl." },
    keno:      { title:"Mander Keno",      desc:"Wähle bis zu 10 Zahlen aus einem 40-Felder-Brett und sieh, wie viele mit den 10 gezogenen Ergebnissen übereinstimmen. Wähle dein Risikolevel für die Auszahlungstabelle." },
    blackjack: { title:"Mander Blackjack", desc:"Spiele klassisches Blackjack mit einem kryptografisch verifizierten 6-Deck-Schuh. Jede Hand wird mit Provably-Fair-Technologie ausgeteilt. Karte ziehen, stehen, verdoppeln oder teilen." },
    mines:     { title:"Mander Mines",     desc:"Navigiere durch ein Minenfeld, entdecke Edelsteine und multipliziere deinen Einsatz. Wähle Rastergröße und Minenanzahl, dann decke Felder einzeln auf." },
    slot:      { title:"Candy Burst",      desc:"Drehe die Walzen und kombiniere Bonbon-Symbole für Gewinne. Spezielle Boni, Multiplikatoren und Freispiele warten auf jeden Spin.", sub:"Slots" },
    hilo:      { title:"Mander Hilo",      desc:"Sag voraus, ob die nächste Karte höher oder niedriger ist. Kette richtige Vorhersagen aneinander, um deinen Einsatz zu vervielfachen oder hebe jederzeit ab." },
    roulette:  { title:"Mander Roulette",  desc:"Europäisches Roulette mit 37 Zahlen (0-36). Setze Chips auf einzelne Zahlen, Spalten, Dutzende oder äußere Wetten. Drehe das Rad und entdecke, wo die Kugel landet." },
    baccarat:  { title:"Mander Baccarat",  desc:"Das klassische Kartenspiel, bei dem du auf den Spieler, die Bank oder ein Unentschieden wettest. Karten werden mit Modulo-10-Summen verteilt und Standard-Drittkarten-Regeln gelten." },
  },
  fr: {
    dice:      { title:"Mander Dés",       desc:"Lancez les dés et pariez si le résultat est supérieur ou inférieur à votre numéro cible. Vous contrôlez la probabilité de gagner et le paiement — plus le risque est élevé, plus la récompense est grande." },
    plinko:    { title:"Mander Plinko",    desc:"Faites tomber une balle depuis le sommet d'une pyramide de chevilles et observez-la rebondir dans un slot multiplicateur. Choisissez votre niveau de risque et le nombre de rangées." },
    keno:      { title:"Mander Keno",      desc:"Choisissez jusqu'à 10 numéros sur un plateau de 40 cases et voyez combien correspondent aux 10 résultats tirés. Sélectionnez votre niveau de risque pour contrôler la table de paiement." },
    blackjack: { title:"Mander Blackjack", desc:"Jouez au Blackjack classique avec un sabot de 6 jeux vérifié cryptographiquement. Chaque main est distribuée avec une technologie provably fair. Tirez, restez, doublez ou divisez." },
    mines:     { title:"Mander Mines",     desc:"Naviguez dans un champ de mines en découvrant des gemmes et en multipliant votre mise. Choisissez la taille de la grille et le nombre de mines, puis révélez les cases une à une." },
    slot:      { title:"Candy Burst",      desc:"Faites tourner les rouleaux et associez des symboles de bonbons pour gagner des prix. Des bonus spéciaux, des multiplicateurs et des tours gratuits vous attendent à chaque spin.", sub:"Slots" },
    hilo:      { title:"Mander Hilo",      desc:"Prédisez si la prochaine carte sera plus haute ou plus basse que la carte actuelle. Enchaînez les bonnes réponses pour multiplier votre mise ou retirez vos gains à tout moment." },
    roulette:  { title:"Mander Roulette",  desc:"Roulette européenne avec 37 numéros (0-36). Placez des jetons sur des numéros individuels, colonnes, douzaines ou mises extérieures. Faites tourner la roue et découvrez où tombe la balle." },
    baccarat:  { title:"Mander Baccarat",  desc:"Le jeu de cartes classique où vous pariez sur le Joueur, le Banquier ou l'Égalité. Les cartes sont distribuées avec des totaux modulo 10 et les règles standard de troisième carte s'appliquent." },
  },
  id: {
    dice:      { title:"Mander Dadu",      desc:"Lempar dadu dan taruhan apakah hasilnya di atas atau di bawah angka target Anda. Anda mengontrol peluang menang dan pembayaran — semakin tinggi risiko, semakin besar hadiah." },
    plinko:    { title:"Mander Plinko",    desc:"Jatuhkan bola dari atas piramida pasak dan saksikan pantulannya ke slot pengali. Pilih tingkat risiko dan jumlah baris untuk mengontrol distribusi pembayaran." },
    keno:      { title:"Mander Keno",      desc:"Pilih hingga 10 angka dari papan 40 kotak dan lihat berapa yang cocok dengan 10 hasil undian. Pilih tingkat risiko untuk mengontrol tabel pembayaran." },
    blackjack: { title:"Mander Blackjack", desc:"Mainkan Blackjack klasik dengan sepatu 6 dek yang diverifikasi secara kriptografis. Setiap tangan dibagikan dengan teknologi provably fair. Minta, berhenti, gandakan, atau bagi." },
    mines:     { title:"Mander Mines",     desc:"Navigasi ladang ranjau dengan menemukan permata dan menggandakan taruhan Anda. Pilih ukuran grid dan jumlah ranjau, lalu ungkap kotak satu per satu." },
    slot:      { title:"Candy Burst",      desc:"Putar gulungan dan cocokkan simbol permen untuk memenangkan hadiah. Bonus khusus, pengali, dan putaran gratis menanti di setiap putaran.", sub:"Slots" },
    hilo:      { title:"Mander Hilo",      desc:"Prediksi apakah kartu berikutnya lebih tinggi atau lebih rendah dari kartu saat ini. Rangkai tebakan yang benar untuk menggandakan taruhan atau tarik kemenangan kapan saja." },
    roulette:  { title:"Mander Roulette",  desc:"Roulette Eropa dengan 37 angka (0-36). Tempatkan chip pada angka tunggal, kolom, lusinan, atau taruhan luar. Putar roda dan temukan di mana bola jatuh." },
    baccarat:  { title:"Mander Baccarat",  desc:"Permainan kartu klasik di mana Anda bertaruh pada Pemain, Bankir, atau Seri. Kartu dibagikan dengan total modulo 10 dan aturan kartu ketiga standar berlaku." },
  },
  it: {
    dice:      { title:"Mander Dadi",      desc:"Lancia i dadi e scommetti se il risultato è sopra o sotto il tuo numero obiettivo. Controlli la probabilità di vincita e il pagamento — maggiore il rischio, maggiore la ricompensa." },
    plinko:    { title:"Mander Plinko",    desc:"Lascia cadere una pallina dalla cima di una piramide di pioli e guarda come rimbalza in uno slot moltiplicatore. Scegli il livello di rischio e il numero di file." },
    keno:      { title:"Mander Keno",      desc:"Scegli fino a 10 numeri da una griglia di 40 caselle e guarda quanti corrispondono ai 10 risultati estratti. Seleziona il tuo livello di rischio per controllare la tabella dei pagamenti." },
    blackjack: { title:"Mander Blackjack", desc:"Gioca al Blackjack classico con una scarpa da 6 mazzi verificata crittograficamente. Ogni mano viene distribuita con tecnologia provably fair. Chiedi, stai, raddoppia o dividi." },
    mines:     { title:"Mander Mine",      desc:"Naviga attraverso un campo minato scoprendo gemme e moltiplicando la tua scommessa. Scegli la dimensione della griglia e il numero di mine, poi rivela caselle una alla volta." },
    slot:      { title:"Candy Burst",      desc:"Gira i rulli e abbina simboli di caramelle per vincere premi. Bonus speciali, moltiplicatori e giri gratis ti aspettano ad ogni spin.", sub:"Slots" },
    hilo:      { title:"Mander Hilo",      desc:"Prevedi se la prossima carta sarà più alta o più bassa di quella attuale. Concatena previsioni corrette per moltiplicare la tua scommessa o ritira le vincite in qualsiasi momento." },
    roulette:  { title:"Mander Roulette",  desc:"Roulette Europea con 37 numeri (0-36). Piazza chip su numeri singoli, colonne, dozzine o puntate esterne. Fai girare la ruota e scopri dove cade la pallina." },
    baccarat:  { title:"Mander Baccarat",  desc:"Il classico gioco di carte dove scommetti sul Giocatore, sul Banco o sul Pareggio. Le carte vengono distribuite con totali modulo 10 e si applicano le regole standard della terza carta." },
  },
  ko: {
    dice:      { title:"맨더 주사위",       desc:"주사위를 굴려 결과가 목표 숫자보다 높은지 낮은지 베팅하세요. 승률과 배당금을 직접 조절할 수 있으며 위험이 클수록 보상도 큽니다." },
    plinko:    { title:"맨더 플링코",       desc:"핀 피라미드 꼭대기에서 공을 떨어뜨려 배율 슬롯에 떨어지는 것을 지켜보세요. 위험 수준과 줄 수를 선택하여 배당 분포를 조정하세요." },
    keno:      { title:"맨더 키노",         desc:"40개 칸 보드에서 최대 10개 번호를 선택하고 추첨된 10개 결과와 몇 개가 일치하는지 확인하세요. 위험 수준을 선택하여 지급 테이블을 조절하세요." },
    blackjack: { title:"맨더 블랙잭",       desc:"암호학적으로 검증된 6덱 슈로 클래식 블랙잭을 플레이하세요. 모든 패는 증명 가능한 공정 기술로 배분됩니다. 히트, 스탠드, 더블, 또는 스플릿." },
    mines:     { title:"맨더 마인즈",       desc:"지뢰밭을 탐험하며 보석을 발견하고 베팅을 배증하세요. 그리드 크기와 지뢰 수를 선택한 후 타일을 하나씩 공개하세요." },
    slot:      { title:"캔디 버스트",       desc:"릴을 돌려 사탕 심볼을 맞추고 상품을 획득하세요. 모든 스핀에서 특별 보너스, 배율, 무료 스핀이 기다립니다.", sub:"슬롯" },
    hilo:      { title:"맨더 하이로",       desc:"다음 카드가 현재 카드보다 높을지 낮을지 예측하세요. 연속 정답으로 베팅을 배증하거나 언제든지 수익을 인출하세요." },
    roulette:  { title:"맨더 룰렛",         desc:"37개 숫자(0-36)의 유럽식 룰렛. 단일 숫자, 열, 다스, 또는 외부 베팅에 칩을 놓으세요. 휠을 돌려 공이 어디 떨어지는지 확인하세요." },
    baccarat:  { title:"맨더 바카라",       desc:"플레이어, 뱅커 또는 타이에 베팅하는 클래식 카드 게임. 카드 합계는 모듈로 10으로 계산되며 표준 세 번째 카드 규칙이 적용됩니다." },
  },
  nl: {
    dice:      { title:"Mander Dobbelstenen", desc:"Gooi de dobbelstenen en wed of het resultaat boven of onder je doelnummer valt. Jij bepaalt de winkans en de uitbetaling — hoe groter het risico, hoe groter de beloning." },
    plinko:    { title:"Mander Plinko",       desc:"Laat een bal vallen van de top van een penpiramide en kijk hoe die stuitert naar een multiplier-slot. Kies je risiconiveau en het aantal rijen." },
    keno:      { title:"Mander Keno",         desc:"Kies tot 10 nummers van een bord met 40 vakjes en kijk hoeveel overeenkomen met de 10 getrokken resultaten. Selecteer je risiconiveau voor de uitbetalingstabel." },
    blackjack: { title:"Mander Blackjack",    desc:"Speel klassiek Blackjack met een cryptografisch geverifieerde 6-deck schoen. Elke hand wordt gedeeld met aantoonbaar eerlijke technologie. Pak, sta, verdubbel of splits." },
    mines:     { title:"Mander Mijnen",       desc:"Navigeer door een mijnenveld en ontdek edelstenen terwijl je je inzet vermenigvuldigt. Kies de rastergrootte en het aantal mijnen, leg dan vakjes een voor een bloot." },
    slot:      { title:"Candy Burst",         desc:"Draai de rollen en combineer snoepsymbolen voor prijzen. Speciale bonussen, vermenigvuldigers en gratis spins wachten bij elke draai.", sub:"Slots" },
    hilo:      { title:"Mander Hilo",         desc:"Voorspel of de volgende kaart hoger of lager is dan de huidige. Keten correcte voorspellingen aaneen om je inzet te vermenigvuldigen of trek op elk moment winst." },
    roulette:  { title:"Mander Roulette",     desc:"Europees roulette met 37 nummers (0-36). Plaats chips op losse nummers, kolommen, tientallen of buitenste weddenschappen. Draai het wiel en ontdek waar de bal landt." },
    baccarat:  { title:"Mander Baccarat",     desc:"Het klassieke kaartspel waarbij je wedt op Speler, Bankier of Gelijkspel. Kaarten worden gedeeld met modulo-10 totalen en standaard derde-kaart regels gelden." },
  },
  pl: {
    dice:      { title:"Mander Kości",     desc:"Rzuć kośćmi i obstawiaj, czy wynik będzie powyżej czy poniżej twojej liczby docelowej. Kontrolujesz szansę wygranej i wypłatę — im większe ryzyko, tym większa nagroda." },
    plinko:    { title:"Mander Plinko",    desc:"Upuść kulkę z wierzchołka piramidy kołków i obserwuj, jak odbija się do slotu mnożnika. Wybierz poziom ryzyka i liczbę rzędów, aby kontrolować rozkład wypłat." },
    keno:      { title:"Mander Keno",      desc:"Wybierz do 10 liczb z planszy 40 pól i sprawdź, ile pasuje do 10 losowanych wyników. Wybierz poziom ryzyka, aby kontrolować tabelę wypłat." },
    blackjack: { title:"Mander Blackjack", desc:"Graj w klasycznego Blackjacka z kryptograficznie zweryfikowanym 6-taliowym butem. Każda ręka jest rozdawana z technologią provably fair. Proś, stój, podwój lub dziel." },
    mines:     { title:"Mander Miny",      desc:"Nawiguj przez pole minowe, odkrywając klejnoty i mnożąc swój zakład. Wybierz rozmiar siatki i liczbę min, a następnie odkrywaj pola jedno po drugim." },
    slot:      { title:"Candy Burst",      desc:"Obracaj bębny i łącz słodkie symbole, aby wygrywać nagrody. Specjalne bonusy, mnożniki i darmowe spiny czekają przy każdym obrocie.", sub:"Slots" },
    hilo:      { title:"Mander Hilo",      desc:"Przewiduj, czy następna karta będzie wyższa czy niższa od obecnej. Łącz poprawne przewidywania, aby mnożyć zakład lub wypłać wygrane w dowolnym momencie." },
    roulette:  { title:"Mander Ruletka",   desc:"Europejska ruletka z 37 numerami (0-36). Kładź żetony na pojedynczych numerach, kolumnach, tuzinach lub zakładach zewnętrznych. Kręć kołem i odkryj, gdzie wyląduje kulka." },
    baccarat:  { title:"Mander Baccarat",  desc:"Klasyczna gra karciana, w której obstawiasz Gracza, Bankiera lub Remis. Karty są rozdawane z sumami modulo 10 i obowiązują standardowe zasady trzeciej karty." },
  },
  ru: {
    dice:      { title:"Мандер Кости",     desc:"Бросайте кости и ставьте, упадёт ли результат выше или ниже вашего целевого числа. Вы контролируете шанс выигрыша и выплату — чем выше риск, тем больше награда." },
    plinko:    { title:"Мандер Плинко",    desc:"Бросайте шарик с вершины пирамиды гвоздей и наблюдайте, как он прыгает в множительный слот. Выбирайте уровень риска и количество рядов для контроля распределения выплат." },
    keno:      { title:"Мандер Кено",      desc:"Выберите до 10 чисел из таблицы 40 ячеек и посмотрите, сколько совпадёт с 10 выпавшими результатами. Выберите уровень риска для управления таблицей выплат." },
    blackjack: { title:"Мандер Блэкджек", desc:"Играйте в классический блэкджек с криптографически проверенной 6-колодной обувью. Каждая рука раздаётся с технологией provably fair. Возьмите карту, стойте, удвойте или разделите." },
    mines:     { title:"Мандер Мины",      desc:"Навигируйте по минному полю, обнаруживая самоцветы и умножая ставку. Выбирайте размер сетки и количество мин, затем открывайте клетки по одной." },
    slot:      { title:"Candy Burst",      desc:"Крутите барабаны и совмещайте конфетные символы для выигрыша. Специальные бонусы, множители и бесплатные спины ждут вас при каждом вращении.", sub:"Слоты" },
    hilo:      { title:"Мандер Хайло",     desc:"Предсказывайте, будет ли следующая карта выше или ниже текущей. Собирайте правильные ответы подряд, чтобы умножить ставку, или снимайте выигрыш в любой момент." },
    roulette:  { title:"Мандер Рулетка",   desc:"Европейская рулетка с 37 числами (0-36). Ставьте фишки на отдельные числа, колонки, дюжины или внешние ставки. Крутите колесо и узнайте, где остановится шарик." },
    baccarat:  { title:"Мандер Баккара",   desc:"Классическая карточная игра, где вы ставите на Игрока, Банкира или Ничью. Карты раздаются с суммами по модулю 10 и действуют стандартные правила третьей карты." },
  },
  tr: {
    dice:      { title:"Mander Zar",       desc:"Zarı atın ve sonucun hedef sayınızın üstünde mi altında mı olduğuna bahis yapın. Kazanma ihtimalini ve ödemeyi siz kontrol edersiniz — risk ne kadar yüksekse ödül de o kadar büyük." },
    plinko:    { title:"Mander Plinko",    desc:"Bir çivi piramidinin tepesinden bir top bırakın ve çarpan slotuna sekerek düşmesini izleyin. Risk seviyenizi ve satır sayısını seçerek ödeme dağılımını kontrol edin." },
    keno:      { title:"Mander Keno",      desc:"40 kutulu tahtadan 10 adede kadar sayı seçin ve 10 çekilen sonuçla kaç tanesinin eşleştiğini görün. Ödeme tablosunu kontrol etmek için risk seviyenizi seçin." },
    blackjack: { title:"Mander Blackjack", desc:"Kriptografik olarak doğrulanmış 6 deste ile klasik Blackjack oynayın. Her el, kanıtlanabilir adil teknoloji ile dağıtılır. Kart çekin, durun, ikiye katlayın veya bölün." },
    mines:     { title:"Mander Mayınlar",  desc:"Mücevher keşfederek ve bahsinizi katlayarak bir mayın tarlasında ilerlerin. Grid boyutunu ve mayın sayısını seçin, ardından karoları teker teker açın." },
    slot:      { title:"Candy Burst",      desc:"Makaraları çevirin ve şeker sembolleri eşleştirerek ödüller kazanın. Özel bonuslar, çarpanlar ve ücretsiz dönüşler her çevrimde sizi bekliyor.", sub:"Slots" },
    hilo:      { title:"Mander Hilo",      desc:"Bir sonraki kartın mevcut karttan yüksek mi alçak mı olacağını tahmin edin. Doğru tahminleri zincirleyerek bahsinizi katlayın veya istediğiniz zaman kazanımlarınızı çekin." },
    roulette:  { title:"Mander Rulet",     desc:"37 sayılı (0-36) Avrupa Ruleti. Tek sayılara, sütunlara, düzinelere veya dış bahislere chip yerleştirin. Tekerleği çevirin ve topun nereye düştüğünü keşfedin." },
    baccarat:  { title:"Mander Baccarat",  desc:"Oyuncu, Banker veya Berabere üzerine bahis yaptığınız klasik kart oyunu. Kartlar modulo-10 toplamlarıyla dağıtılır ve standart üçüncü kart kuralları uygulanır." },
  },
};

type SectionKey = "howToPlay"|"winProb"|"provablyFair"|"riskLevels"|"riskPayouts"|"yourOptions"|"payouts"|"multRisk"|"dynamicMult"|"cashOrContinue"|"specialFeatures"|"betTypes"|"autoMode"|"cardValues"|"thirdCard"|"learnMore";

const SECTION_TRANS: Record<string, Record<SectionKey, string>> = {
  es: {
    howToPlay:       "CÓMO JUGAR",
    winProb:         "PROBABILIDAD Y PAGOS",
    provablyFair:    "VERIFICACIÓN PROVABLY FAIR",
    riskLevels:      "NIVELES DE RIESGO",
    riskPayouts:     "NIVELES DE RIESGO Y PAGOS",
    yourOptions:     "TUS OPCIONES",
    payouts:         "PAGOS",
    multRisk:        "MULTIPLICADOR Y RIESGO",
    dynamicMult:     "MULTIPLICADORES DINÁMICOS",
    cashOrContinue:  "RETIRAR O CONTINUAR",
    specialFeatures: "CARACTERÍSTICAS ESPECIALES",
    betTypes:        "TIPOS DE APUESTA Y PAGOS",
    autoMode:        "MODO AUTOMÁTICO",
    cardValues:      "VALORES DE CARTA",
    thirdCard:       "REGLAS DE TERCERA CARTA",
    learnMore:       "Aprende más sobre verificación de equidad →",
  },
  en: {
    howToPlay:       "HOW TO PLAY",
    winProb:         "WIN PROBABILITY & PAYOUTS",
    provablyFair:    "PROVABLY FAIR VERIFICATION",
    riskLevels:      "RISK LEVELS",
    riskPayouts:     "RISK LEVELS & PAYOUTS",
    yourOptions:     "YOUR OPTIONS",
    payouts:         "PAYOUTS",
    multRisk:        "MULTIPLIER & RISK",
    dynamicMult:     "DYNAMIC MULTIPLIERS",
    cashOrContinue:  "CASH OUT OR CONTINUE",
    specialFeatures: "SPECIAL FEATURES",
    betTypes:        "BET TYPES & PAYOUTS",
    autoMode:        "AUTO MODE",
    cardValues:      "CARD VALUES",
    thirdCard:       "THIRD CARD RULES",
    learnMore:       "Learn more about provably fair →",
  },
  pt: {
    howToPlay:       "COMO JOGAR",
    winProb:         "PROBABILIDADE E PAGAMENTOS",
    provablyFair:    "VERIFICAÇÃO PROVABLY FAIR",
    riskLevels:      "NÍVEIS DE RISCO",
    riskPayouts:     "NÍVEIS DE RISCO E PAGAMENTOS",
    yourOptions:     "SUAS OPÇÕES",
    payouts:         "PAGAMENTOS",
    multRisk:        "MULTIPLICADOR E RISCO",
    dynamicMult:     "MULTIPLICADORES DINÂMICOS",
    cashOrContinue:  "SACAR OU CONTINUAR",
    specialFeatures: "RECURSOS ESPECIAIS",
    betTypes:        "TIPOS DE APOSTA E PAGAMENTOS",
    autoMode:        "MODO AUTOMÁTICO",
    cardValues:      "VALORES DAS CARTAS",
    thirdCard:       "REGRAS DA TERCEIRA CARTA",
    learnMore:       "Saiba mais sobre verificação provably fair →",
  },
  de: {
    howToPlay:       "SO SPIELST DU",
    winProb:         "GEWINNWAHRSCHEINLICHKEIT & AUSZAHLUNGEN",
    provablyFair:    "PROVABLY FAIR VERIFIZIERUNG",
    riskLevels:      "RISIKOLEVELS",
    riskPayouts:     "RISIKOLEVELS & AUSZAHLUNGEN",
    yourOptions:     "DEINE OPTIONEN",
    payouts:         "AUSZAHLUNGEN",
    multRisk:        "MULTIPLIKATOR & RISIKO",
    dynamicMult:     "DYNAMISCHE MULTIPLIKATOREN",
    cashOrContinue:  "AUSZAHLEN ODER WEITERMACHEN",
    specialFeatures: "BESONDERE FUNKTIONEN",
    betTypes:        "WETTARTEN & AUSZAHLUNGEN",
    autoMode:        "AUTO-MODUS",
    cardValues:      "KARTENWERTE",
    thirdCard:       "DRITTE-KARTE-REGELN",
    learnMore:       "Mehr über Provably Fair erfahren →",
  },
  fr: {
    howToPlay:       "COMMENT JOUER",
    winProb:         "PROBABILITÉ ET PAIEMENTS",
    provablyFair:    "VÉRIFICATION PROVABLY FAIR",
    riskLevels:      "NIVEAUX DE RISQUE",
    riskPayouts:     "NIVEAUX DE RISQUE ET PAIEMENTS",
    yourOptions:     "VOS OPTIONS",
    payouts:         "PAIEMENTS",
    multRisk:        "MULTIPLICATEUR ET RISQUE",
    dynamicMult:     "MULTIPLICATEURS DYNAMIQUES",
    cashOrContinue:  "ENCAISSER OU CONTINUER",
    specialFeatures: "FONCTIONNALITÉS SPÉCIALES",
    betTypes:        "TYPES DE PARIS ET PAIEMENTS",
    autoMode:        "MODE AUTOMATIQUE",
    cardValues:      "VALEURS DES CARTES",
    thirdCard:       "RÈGLES DE LA TROISIÈME CARTE",
    learnMore:       "En savoir plus sur le provably fair →",
  },
  id: {
    howToPlay:       "CARA BERMAIN",
    winProb:         "PELUANG MENANG & PEMBAYARAN",
    provablyFair:    "VERIFIKASI PROVABLY FAIR",
    riskLevels:      "TINGKAT RISIKO",
    riskPayouts:     "TINGKAT RISIKO & PEMBAYARAN",
    yourOptions:     "PILIHAN ANDA",
    payouts:         "PEMBAYARAN",
    multRisk:        "PENGALI & RISIKO",
    dynamicMult:     "PENGALI DINAMIS",
    cashOrContinue:  "TARIK ATAU LANJUT",
    specialFeatures: "FITUR KHUSUS",
    betTypes:        "JENIS TARUHAN & PEMBAYARAN",
    autoMode:        "MODE OTOMATIS",
    cardValues:      "NILAI KARTU",
    thirdCard:       "ATURAN KARTU KETIGA",
    learnMore:       "Pelajari lebih lanjut tentang provably fair →",
  },
  it: {
    howToPlay:       "COME GIOCARE",
    winProb:         "PROBABILITÀ E PAGAMENTI",
    provablyFair:    "VERIFICA PROVABLY FAIR",
    riskLevels:      "LIVELLI DI RISCHIO",
    riskPayouts:     "LIVELLI DI RISCHIO E PAGAMENTI",
    yourOptions:     "LE TUE OPZIONI",
    payouts:         "PAGAMENTI",
    multRisk:        "MOLTIPLICATORE E RISCHIO",
    dynamicMult:     "MOLTIPLICATORI DINAMICI",
    cashOrContinue:  "RITIRARE O CONTINUARE",
    specialFeatures: "FUNZIONI SPECIALI",
    betTypes:        "TIPI DI PUNTATA E PAGAMENTI",
    autoMode:        "MODALITÀ AUTO",
    cardValues:      "VALORI DELLE CARTE",
    thirdCard:       "REGOLE DELLA TERZA CARTA",
    learnMore:       "Scopri di più sul provably fair →",
  },
  ko: {
    howToPlay:       "게임 방법",
    winProb:         "승률 및 배당금",
    provablyFair:    "공정성 검증",
    riskLevels:      "위험 수준",
    riskPayouts:     "위험 수준 및 배당금",
    yourOptions:     "당신의 선택",
    payouts:         "배당금",
    multRisk:        "배율 및 위험",
    dynamicMult:     "동적 배율",
    cashOrContinue:  "인출 또는 계속",
    specialFeatures: "특별 기능",
    betTypes:        "베팅 유형 및 배당금",
    autoMode:        "자동 모드",
    cardValues:      "카드 값",
    thirdCard:       "세 번째 카드 규칙",
    learnMore:       "공정성 검증에 대해 자세히 알아보기 →",
  },
  nl: {
    howToPlay:       "HOE TE SPELEN",
    winProb:         "WINKANS & UITBETALINGEN",
    provablyFair:    "AANTOONBAAR EERLIJKE VERIFICATIE",
    riskLevels:      "RISICONIVEAUS",
    riskPayouts:     "RISICONIVEAUS & UITBETALINGEN",
    yourOptions:     "JOUW OPTIES",
    payouts:         "UITBETALINGEN",
    multRisk:        "VERMENIGVULDIGER & RISICO",
    dynamicMult:     "DYNAMISCHE VERMENIGVULDIGERS",
    cashOrContinue:  "UITCASHEN OF DOORGAAN",
    specialFeatures: "SPECIALE FUNCTIES",
    betTypes:        "WEDTYPES & UITBETALINGEN",
    autoMode:        "AUTO-MODUS",
    cardValues:      "KAARTWAARDEN",
    thirdCard:       "DERDE-KAART REGELS",
    learnMore:       "Meer leren over aantoonbaar eerlijk →",
  },
  pl: {
    howToPlay:       "JAK GRAĆ",
    winProb:         "SZANSA WYGRANEJ I WYPŁATY",
    provablyFair:    "WERYFIKACJA PROVABLY FAIR",
    riskLevels:      "POZIOMY RYZYKA",
    riskPayouts:     "POZIOMY RYZYKA I WYPŁATY",
    yourOptions:     "TWOJE OPCJE",
    payouts:         "WYPŁATY",
    multRisk:        "MNOŻNIK I RYZYKO",
    dynamicMult:     "DYNAMICZNE MNOŻNIKI",
    cashOrContinue:  "WYPŁATA LUB KONTYNUACJA",
    specialFeatures: "SPECJALNE FUNKCJE",
    betTypes:        "TYPY ZAKŁADÓW I WYPŁATY",
    autoMode:        "TRYB AUTO",
    cardValues:      "WARTOŚCI KART",
    thirdCard:       "ZASADY TRZECIEJ KARTY",
    learnMore:       "Dowiedz się więcej o provably fair →",
  },
  ru: {
    howToPlay:       "КАК ИГРАТЬ",
    winProb:         "ВЕРОЯТНОСТЬ ВЫИГРЫША И ВЫПЛАТЫ",
    provablyFair:    "ВЕРИФИКАЦИЯ PROVABLY FAIR",
    riskLevels:      "УРОВНИ РИСКА",
    riskPayouts:     "УРОВНИ РИСКА И ВЫПЛАТЫ",
    yourOptions:     "ВАШИ ВАРИАНТЫ",
    payouts:         "ВЫПЛАТЫ",
    multRisk:        "МНОЖИТЕЛЬ И РИСК",
    dynamicMult:     "ДИНАМИЧЕСКИЕ МНОЖИТЕЛИ",
    cashOrContinue:  "ВЫВЕСТИ ИЛИ ПРОДОЛЖИТЬ",
    specialFeatures: "ОСОБЫЕ ФУНКЦИИ",
    betTypes:        "ТИПЫ СТАВОК И ВЫПЛАТЫ",
    autoMode:        "РЕЖИМ АВТО",
    cardValues:      "ЗНАЧЕНИЯ КАРТ",
    thirdCard:       "ПРАВИЛА ТРЕТЬЕЙ КАРТЫ",
    learnMore:       "Узнать больше о provably fair →",
  },
  tr: {
    howToPlay:       "NASIL OYNANIR",
    winProb:         "KAZANMA İHTİMALİ VE ÖDEMELER",
    provablyFair:    "PROVABLY FAIR DOĞRULAMASI",
    riskLevels:      "RİSK SEVİYELERİ",
    riskPayouts:     "RİSK SEVİYELERİ VE ÖDEMELER",
    yourOptions:     "SEÇENEKLERİNİZ",
    payouts:         "ÖDEMELER",
    multRisk:        "ÇARPAN VE RİSK",
    dynamicMult:     "DİNAMİK ÇARPANLAR",
    cashOrContinue:  "ÇEKMEK VEYA DEVAM ETMEK",
    specialFeatures: "ÖZEL ÖZELLİKLER",
    betTypes:        "BAHİS TÜRLERİ VE ÖDEMELER",
    autoMode:        "OTO MODU",
    cardValues:      "KART DEĞERLERİ",
    thirdCard:       "ÜÇÜNCÜ KART KURALLARI",
    learnMore:       "Provably fair hakkında daha fazla bilgi →",
  },
};

type BulletKey = string;
const BULLET_TRANS: Record<string, Record<string,string>> = {
  es: {
    lowRiskLabel:"Riesgo Bajo", lowRiskText:"Los multiplicadores están distribuidos de forma más uniforme. La mayoría de las caídas devuelven cerca de tu apuesta con multiplicadores extremos más pequeños.",
    medRiskLabel:"Riesgo Medio", medRiskText:"Una distribución equilibrada con multiplicadores altos moderados y pérdidas pequeñas más frecuentes.",
    highRiskLabel:"Riesgo Alto", highRiskText:"Multiplicadores extremos en los bordes pero la mayoría de las caídas devuelven 0x. Alta varianza, alta recompensa.",
    classicLabel:"Clásico", classicText:"Pagos equilibrados en todos los conteos de aciertos.",
    lowLabel:"Bajo", lowText:"Ganancias pequeñas frecuentes, pagos máximos moderados.",
    medLabel:"Medio", medText:"Menos ganancias pero multiplicadores más altos en más coincidencias.",
    highLabel:"Alto", highText:"La mayoría pagan 0x, pero acertar todos paga hasta 1,000x.",
    hitLabel:"Pedir", hitText:"Saca otra carta del zapato.",
    standLabel:"Plantarse", standText:"Conserva tu mano actual y deja jugar al crupier.",
    doubleLabel:"Doblar", doubleText:"Dobla tu apuesta, saca exactamente una carta más, luego te plantas.",
    splitLabel:"Dividir", splitText:"Si tus primeras dos cartas tienen el mismo valor, divídelas en dos manos separadas.",
    insuranceLabel:"Seguro", insuranceText:"Cuando el crupier muestra un As, puedes hacer una apuesta lateral que paga 2:1 si tiene Blackjack.",
    fewerMinesLabel:"Menos minas", fewerMinesText:"Incrementos de multiplicador más pequeños por revelación, pero menor riesgo.",
    moreMinesLabel:"Más minas", moreMinesText:"Saltos de multiplicador más grandes, pero mayor probabilidad de golpear una mina.",
    biggerGridLabel:"Cuadrículas más grandes", biggerGridText:"Dan más casillas para explorar con mayor profundidad estratégica.",
    wildLabel:"Wild", wildText:"Sustituye cualquier símbolo normal para completar combinaciones ganadoras.",
    scatterLabel:"Scatter", scatterText:"Activa giros gratis sin importar su posición en los carretes.",
    freeSpinsLabel:"Giros Gratis", freeSpinsText:"Rondas adicionales sin costo donde todos los premios se multiplican.",
    straightLabel:"Número exacto (Pleno)", straightText:"Apuesta a un número específico. Paga 35:1.",
    columnLabel:"Columna (2:1)", columnText:"Cada fila del tablero (12 números). Paga 2:1.",
    dozenLabel:"Docena (2:1)", dozenText:"1-12, 13-24 o 25-36. Paga 2:1.",
    evenMoneyLabel:"Dinero par (1:1)", evenMoneyText:"Rojo/Negro, Par/Impar, Bajo/Alto. Paga 1:1. El 0 pierde todas las apuestas externas.",
    playerLabel:"Jugador (1:1)", playerText:"Si la mano del Jugador tiene mayor valor que la Banca, ganás el doble.",
    bankerLabel:"Banca (0.95:1)", bankerText:"Si la Banca gana, cobras con 5% de comisión. Retorno efectivo 1.95x.",
    tieLabel:"Empate (8:1)", tieText:"Si ambas manos terminan igual, ganás 8x tu apuesta.",
  },
  en: {
    lowRiskLabel:"Low Risk", lowRiskText:"Multipliers are distributed more evenly. Most drops return close to your bet with smaller extreme multipliers.",
    medRiskLabel:"Medium Risk", medRiskText:"A balanced distribution with moderate high multipliers and more frequent small losses.",
    highRiskLabel:"High Risk", highRiskText:"Extreme multipliers at the edges but most drops return 0x. High variance, high reward.",
    classicLabel:"Classic", classicText:"Balanced payouts across all match counts.",
    lowLabel:"Low", lowText:"Frequent small wins, moderate maximum payouts.",
    medLabel:"Medium", medText:"Fewer wins but higher multipliers on more matches.",
    highLabel:"High", highText:"Most combos pay 0x, but hitting all pays up to 1,000x.",
    hitLabel:"Hit", hitText:"Draw another card from the shoe.",
    standLabel:"Stand", standText:"Keep your current hand and let the dealer play.",
    doubleLabel:"Double Down", doubleText:"Double your bet, take exactly one more card, then stand.",
    splitLabel:"Split", splitText:"If your first two cards have the same value, split them into two separate hands.",
    insuranceLabel:"Insurance", insuranceText:"When the dealer shows an Ace, you can make a side bet paying 2:1 if the dealer has Blackjack.",
    fewerMinesLabel:"Fewer mines", fewerMinesText:"Smaller multiplier increments per reveal, but lower risk.",
    moreMinesLabel:"More mines", moreMinesText:"Larger multiplier jumps, but higher chance of hitting a mine.",
    biggerGridLabel:"Bigger grids", biggerGridText:"More tiles to explore with greater strategic depth.",
    wildLabel:"Wild", wildText:"Substitutes any normal symbol to complete winning combinations.",
    scatterLabel:"Scatter", scatterText:"Activates free spins regardless of position on the reels.",
    freeSpinsLabel:"Free Spins", freeSpinsText:"Extra rounds at no cost where all prizes are multiplied.",
    straightLabel:"Straight Up", straightText:"Bet on a specific number. Pays 35:1.",
    columnLabel:"Column (2:1)", columnText:"Each column on the board (12 numbers). Pays 2:1.",
    dozenLabel:"Dozen (2:1)", dozenText:"1-12, 13-24 or 25-36. Pays 2:1.",
    evenMoneyLabel:"Even Money (1:1)", evenMoneyText:"Red/Black, Odd/Even, Low/High. Pays 1:1. 0 loses all outside bets.",
    playerLabel:"Player (1:1)", playerText:"If the Player hand has a higher value than the Banker, you win double.",
    bankerLabel:"Banker (0.95:1)", bankerText:"If the Banker wins, you receive your payout with a 5% commission. Effective return 1.95x.",
    tieLabel:"Tie (8:1)", tieText:"If both hands end with equal value, you win 8x your bet.",
  },
  pt: {
    lowRiskLabel:"Risco Baixo", lowRiskText:"Multiplicadores distribuídos de forma mais uniforme. A maioria das quedas retorna perto de sua aposta.",
    medRiskLabel:"Risco Médio", medRiskText:"Distribuição equilibrada com multiplicadores altos moderados e perdas pequenas mais frequentes.",
    highRiskLabel:"Risco Alto", highRiskText:"Multiplicadores extremos nas bordas, mas a maioria das quedas retorna 0x. Alta variância.",
    classicLabel:"Clássico", classicText:"Pagamentos equilibrados em todas as contagens de acertos.",
    lowLabel:"Baixo", lowText:"Ganhos pequenos frequentes, pagamentos máximos moderados.",
    medLabel:"Médio", medText:"Menos ganhos, mas multiplicadores mais altos em mais coincidências.",
    highLabel:"Alto", highText:"A maioria paga 0x, mas acertar todos paga até 1.000x.",
    hitLabel:"Pedir", hitText:"Compre outra carta.",
    standLabel:"Parar", standText:"Mantenha sua mão atual e deixe o dealer jogar.",
    doubleLabel:"Dobrar", doubleText:"Dobre sua aposta, compre mais uma carta, depois pare.",
    splitLabel:"Dividir", splitText:"Se suas primeiras duas cartas têm o mesmo valor, divida em duas mãos separadas.",
    insuranceLabel:"Seguro", insuranceText:"Quando o dealer mostra um Ás, você pode fazer uma aposta lateral que paga 2:1 se tiver Blackjack.",
    fewerMinesLabel:"Menos minas", fewerMinesText:"Incrementos de multiplicador menores por revelação, mas menor risco.",
    moreMinesLabel:"Mais minas", moreMinesText:"Saltos de multiplicador maiores, mas maior probabilidade de atingir uma mina.",
    biggerGridLabel:"Grades maiores", biggerGridText:"Mais casas para explorar com maior profundidade estratégica.",
    wildLabel:"Wild", wildText:"Substitui qualquer símbolo normal para completar combinações vencedoras.",
    scatterLabel:"Scatter", scatterText:"Ativa giros grátis independente da posição nos rolos.",
    freeSpinsLabel:"Giros Grátis", freeSpinsText:"Rodadas extras sem custo onde todos os prêmios são multiplicados.",
    straightLabel:"Número exato", straightText:"Aposta em um número específico. Paga 35:1.",
    columnLabel:"Coluna (2:1)", columnText:"Cada coluna do tabuleiro (12 números). Paga 2:1.",
    dozenLabel:"Dúzia (2:1)", dozenText:"1-12, 13-24 ou 25-36. Paga 2:1.",
    evenMoneyLabel:"Dinheiro par (1:1)", evenMoneyText:"Vermelho/Preto, Par/Ímpar, Baixo/Alto. Paga 1:1.",
    playerLabel:"Jogador (1:1)", playerText:"Se a mão do Jogador tem maior valor que a do Banco, você ganha o dobro.",
    bankerLabel:"Banco (0.95:1)", bankerText:"Se o Banco vencer, você recebe com 5% de comissão. Retorno efetivo 1.95x.",
    tieLabel:"Empate (8:1)", tieText:"Se ambas as mãos terminarem com o mesmo valor, você ganha 8x sua aposta.",
  },
  de: {
    lowRiskLabel:"Niedriges Risiko", lowRiskText:"Gleichmäßiger verteilte Multiplikatoren. Die meisten Würfe geben nahe deinem Einsatz zurück.",
    medRiskLabel:"Mittleres Risiko", medRiskText:"Ausgewogene Verteilung mit moderat hohen Multiplikatoren und häufigeren kleinen Verlusten.",
    highRiskLabel:"Hohes Risiko", highRiskText:"Extreme Multiplikatoren an den Rändern, aber die meisten Würfe geben 0x zurück.",
    classicLabel:"Klassisch", classicText:"Ausgewogene Auszahlungen bei allen Trefferanzahlen.",
    lowLabel:"Niedrig", lowText:"Häufige kleine Gewinne, moderate Höchstauszahlungen.",
    medLabel:"Mittel", medText:"Weniger Gewinne, aber höhere Multiplikatoren bei mehr Treffern.",
    highLabel:"Hoch", highText:"Die meisten Kombinationen zahlen 0x, aber alle treffen zahlt bis zu 1.000x.",
    hitLabel:"Ziehen", hitText:"Ziehe eine weitere Karte.",
    standLabel:"Stehen", standText:"Behalte deine aktuelle Hand und lass den Dealer spielen.",
    doubleLabel:"Verdoppeln", doubleText:"Verdopple deinen Einsatz, ziehe genau eine Karte mehr, dann stehen.",
    splitLabel:"Teilen", splitText:"Wenn deine ersten beiden Karten den gleichen Wert haben, teile sie in zwei Hände auf.",
    insuranceLabel:"Versicherung", insuranceText:"Wenn der Dealer ein Ass zeigt, kannst du eine Seitenwette machen, die 2:1 zahlt, wenn er Blackjack hat.",
    fewerMinesLabel:"Weniger Minen", fewerMinesText:"Kleinere Multiplikatorschritte pro Aufdeckung, aber geringeres Risiko.",
    moreMinesLabel:"Mehr Minen", moreMinesText:"Größere Multiplikatorsprünge, aber höhere Chance eine Mine zu treffen.",
    biggerGridLabel:"Größere Raster", biggerGridText:"Mehr Felder zum Erkunden mit größerer strategischer Tiefe.",
    wildLabel:"Wild", wildText:"Ersetzt jedes normale Symbol, um Gewinnkombinationen zu vervollständigen.",
    scatterLabel:"Scatter", scatterText:"Aktiviert Freispiele unabhängig von der Position auf den Walzen.",
    freeSpinsLabel:"Freispiele", freeSpinsText:"Zusätzliche Runden kostenlos, bei denen alle Gewinne multipliziert werden.",
    straightLabel:"Direkt (Plein)", straightText:"Wette auf eine bestimmte Zahl. Zahlt 35:1.",
    columnLabel:"Spalte (2:1)", columnText:"Jede Spalte des Bretts (12 Zahlen). Zahlt 2:1.",
    dozenLabel:"Dutzend (2:1)", dozenText:"1-12, 13-24 oder 25-36. Zahlt 2:1.",
    evenMoneyLabel:"Einfache Chance (1:1)", evenMoneyText:"Rot/Schwarz, Gerade/Ungerade, Niedrig/Hoch. Zahlt 1:1.",
    playerLabel:"Spieler (1:1)", playerText:"Wenn die Spielerhand höher ist als die Bank, gewinnst du das Doppelte.",
    bankerLabel:"Bank (0.95:1)", bankerText:"Wenn die Bank gewinnt, erhältst du deine Auszahlung mit 5% Provision.",
    tieLabel:"Unentschieden (8:1)", tieText:"Wenn beide Hände gleich enden, gewinnst du 8x deinen Einsatz.",
  },
  fr: {
    lowRiskLabel:"Risque Faible", lowRiskText:"Multiplicateurs distribués plus uniformément. La plupart des chutes retournent près de votre mise.",
    medRiskLabel:"Risque Moyen", medRiskText:"Distribution équilibrée avec des multiplicateurs modérément élevés et des petites pertes plus fréquentes.",
    highRiskLabel:"Risque Élevé", highRiskText:"Multiplicateurs extrêmes sur les bords mais la plupart des chutes retournent 0x.",
    classicLabel:"Classique", classicText:"Paiements équilibrés sur tous les nombres de correspondances.",
    lowLabel:"Bas", lowText:"Petits gains fréquents, paiements maximums modérés.",
    medLabel:"Moyen", medText:"Moins de gains mais multiplicateurs plus élevés sur plus de correspondances.",
    highLabel:"Haut", highText:"La plupart paient 0x, mais tout correspondre paie jusqu'à 1 000x.",
    hitLabel:"Tirer", hitText:"Prenez une autre carte.",
    standLabel:"Rester", standText:"Gardez votre main actuelle et laissez le croupier jouer.",
    doubleLabel:"Doubler", doubleText:"Doublez votre mise, prenez exactement une carte de plus, puis restez.",
    splitLabel:"Séparer", splitText:"Si vos deux premières cartes ont la même valeur, séparez-les en deux mains distinctes.",
    insuranceLabel:"Assurance", insuranceText:"Quand le croupier montre un As, vous pouvez faire un pari annexe payant 2:1 s'il a un Blackjack.",
    fewerMinesLabel:"Moins de mines", fewerMinesText:"Incréments de multiplicateur plus petits par révélation, mais risque plus faible.",
    moreMinesLabel:"Plus de mines", moreMinesText:"Sauts de multiplicateur plus grands, mais plus grande probabilité de toucher une mine.",
    biggerGridLabel:"Grilles plus grandes", biggerGridText:"Plus de cases à explorer avec une profondeur stratégique accrue.",
    wildLabel:"Wild", wildText:"Remplace n'importe quel symbole normal pour compléter des combinaisons gagnantes.",
    scatterLabel:"Scatter", scatterText:"Active des tours gratuits quelle que soit sa position sur les rouleaux.",
    freeSpinsLabel:"Tours Gratuits", freeSpinsText:"Tours supplémentaires gratuits où tous les prix sont multipliés.",
    straightLabel:"Numéro exact (Plein)", straightText:"Pariez sur un numéro spécifique. Paie 35:1.",
    columnLabel:"Colonne (2:1)", columnText:"Chaque colonne du tableau (12 numéros). Paie 2:1.",
    dozenLabel:"Douzaine (2:1)", dozenText:"1-12, 13-24 ou 25-36. Paie 2:1.",
    evenMoneyLabel:"Mise simple (1:1)", evenMoneyText:"Rouge/Noir, Pair/Impair, Bas/Haut. Paie 1:1.",
    playerLabel:"Joueur (1:1)", playerText:"Si la main du Joueur a une valeur plus élevée que celle du Banquier, vous gagnez le double.",
    bankerLabel:"Banquier (0.95:1)", bankerText:"Si le Banquier gagne, vous recevez votre paiement avec une commission de 5%.",
    tieLabel:"Égalité (8:1)", tieText:"Si les deux mains se terminent à égalité, vous gagnez 8x votre mise.",
  },
  id: {
    lowRiskLabel:"Risiko Rendah", lowRiskText:"Pengali terdistribusi lebih merata. Sebagian besar jatuhan mengembalikan mendekati taruhan Anda.",
    medRiskLabel:"Risiko Sedang", medRiskText:"Distribusi seimbang dengan pengali tinggi moderat dan kerugian kecil lebih sering.",
    highRiskLabel:"Risiko Tinggi", highRiskText:"Pengali ekstrem di tepi tetapi sebagian besar jatuhan mengembalikan 0x.",
    classicLabel:"Klasik", classicText:"Pembayaran seimbang di semua jumlah kecocokan.",
    lowLabel:"Rendah", lowText:"Kemenangan kecil yang sering, pembayaran maksimum sedang.",
    medLabel:"Sedang", medText:"Lebih sedikit kemenangan tetapi pengali lebih tinggi pada lebih banyak kecocokan.",
    highLabel:"Tinggi", highText:"Sebagian besar kombinasi membayar 0x, tetapi mencocokkan semua membayar hingga 1.000x.",
    hitLabel:"Minta", hitText:"Ambil kartu lain dari sepatu.",
    standLabel:"Berhenti", standText:"Pertahankan tangan Anda dan biarkan dealer bermain.",
    doubleLabel:"Gandakan", doubleText:"Gandakan taruhan Anda, ambil satu kartu lagi, lalu berhenti.",
    splitLabel:"Pisah", splitText:"Jika dua kartu pertama Anda memiliki nilai yang sama, pisahkan menjadi dua tangan terpisah.",
    insuranceLabel:"Asuransi", insuranceText:"Ketika dealer menunjukkan As, Anda dapat membuat taruhan sampingan yang membayar 2:1 jika dealer memiliki Blackjack.",
    fewerMinesLabel:"Lebih sedikit ranjau", fewerMinesText:"Kenaikan pengali lebih kecil per pengungkapan, tetapi risiko lebih rendah.",
    moreMinesLabel:"Lebih banyak ranjau", moreMinesText:"Lompatan pengali lebih besar, tetapi peluang lebih tinggi mengenai ranjau.",
    biggerGridLabel:"Grid lebih besar", biggerGridText:"Lebih banyak kotak untuk dijelajahi dengan kedalaman strategis lebih besar.",
    wildLabel:"Wild", wildText:"Menggantikan simbol normal apa pun untuk melengkapi kombinasi pemenang.",
    scatterLabel:"Scatter", scatterText:"Mengaktifkan putaran gratis terlepas dari posisi di gulungan.",
    freeSpinsLabel:"Putaran Gratis", freeSpinsText:"Putaran tambahan gratis di mana semua hadiah dikalikan.",
    straightLabel:"Nomor tepat", straightText:"Taruhan pada nomor tertentu. Membayar 35:1.",
    columnLabel:"Kolom (2:1)", columnText:"Setiap kolom papan (12 nomor). Membayar 2:1.",
    dozenLabel:"Selusin (2:1)", dozenText:"1-12, 13-24 atau 25-36. Membayar 2:1.",
    evenMoneyLabel:"Uang genap (1:1)", evenMoneyText:"Merah/Hitam, Ganjil/Genap, Rendah/Tinggi. Membayar 1:1.",
    playerLabel:"Pemain (1:1)", playerText:"Jika tangan Pemain lebih tinggi dari Banker, Anda menang dua kali lipat.",
    bankerLabel:"Banker (0.95:1)", bankerText:"Jika Banker menang, Anda menerima pembayaran dengan komisi 5%.",
    tieLabel:"Seri (8:1)", tieText:"Jika kedua tangan berakhir sama, Anda menang 8x taruhan Anda.",
  },
  it: {
    lowRiskLabel:"Rischio Basso", lowRiskText:"Moltiplicatori distribuiti in modo più uniforme. La maggior parte delle cadute restituisce vicino alla tua scommessa.",
    medRiskLabel:"Rischio Medio", medRiskText:"Distribuzione equilibrata con moltiplicatori alti moderati e perdite piccole più frequenti.",
    highRiskLabel:"Rischio Alto", highRiskText:"Moltiplicatori estremi ai bordi ma la maggior parte delle cadute restituisce 0x.",
    classicLabel:"Classico", classicText:"Pagamenti equilibrati su tutti i conteggi di corrispondenza.",
    lowLabel:"Basso", lowText:"Piccole vincite frequenti, pagamenti massimi moderati.",
    medLabel:"Medio", medText:"Meno vincite ma moltiplicatori più alti su più corrispondenze.",
    highLabel:"Alto", highText:"La maggior parte paga 0x, ma indovinare tutti paga fino a 1.000x.",
    hitLabel:"Chiedere", hitText:"Pesca un'altra carta.",
    standLabel:"Stare", standText:"Mantieni la tua mano attuale e lascia giocare il croupier.",
    doubleLabel:"Raddoppiare", doubleText:"Raddoppia la tua scommessa, pesca esattamente un'altra carta, poi stai.",
    splitLabel:"Dividere", splitText:"Se le tue prime due carte hanno lo stesso valore, dividile in due mani separate.",
    insuranceLabel:"Assicurazione", insuranceText:"Quando il croupier mostra un Asso, puoi fare una scommessa laterale che paga 2:1 se ha Blackjack.",
    fewerMinesLabel:"Meno mine", fewerMinesText:"Incrementi di moltiplicatore più piccoli per ogni rivelazione, ma rischio minore.",
    moreMinesLabel:"Più mine", moreMinesText:"Salti di moltiplicatore più grandi, ma maggiore probabilità di colpire una mina.",
    biggerGridLabel:"Griglie più grandi", biggerGridText:"Più caselle da esplorare con maggiore profondità strategica.",
    wildLabel:"Wild", wildText:"Sostituisce qualsiasi simbolo normale per completare combinazioni vincenti.",
    scatterLabel:"Scatter", scatterText:"Attiva giri gratuiti indipendentemente dalla posizione sui rulli.",
    freeSpinsLabel:"Giri Gratuiti", freeSpinsText:"Round aggiuntivi gratuiti dove tutti i premi vengono moltiplicati.",
    straightLabel:"Numero esatto (Plein)", straightText:"Scommetti su un numero specifico. Paga 35:1.",
    columnLabel:"Colonna (2:1)", columnText:"Ogni colonna del tabellone (12 numeri). Paga 2:1.",
    dozenLabel:"Dozzina (2:1)", dozenText:"1-12, 13-24 o 25-36. Paga 2:1.",
    evenMoneyLabel:"Denaro pari (1:1)", evenMoneyText:"Rosso/Nero, Pari/Dispari, Basso/Alto. Paga 1:1.",
    playerLabel:"Giocatore (1:1)", playerText:"Se la mano del Giocatore ha valore più alto della Banca, vinci il doppio.",
    bankerLabel:"Banca (0.95:1)", bankerText:"Se la Banca vince, ricevi il pagamento con commissione del 5%.",
    tieLabel:"Pareggio (8:1)", tieText:"Se entrambe le mani finiscono con lo stesso valore, vinci 8x la tua scommessa.",
  },
  ko: {
    lowRiskLabel:"낮은 위험", lowRiskText:"배율이 더 고르게 분포됩니다. 대부분의 낙하는 베팅에 가깝게 반환됩니다.",
    medRiskLabel:"중간 위험", medRiskText:"중간 높은 배율과 더 자주 발생하는 작은 손실의 균형 잡힌 분포.",
    highRiskLabel:"높은 위험", highRiskText:"가장자리에 극단적인 배율이 있지만 대부분의 낙하는 0x를 반환합니다.",
    classicLabel:"클래식", classicText:"모든 적중 횟수에 걸쳐 균형 잡힌 배당금.",
    lowLabel:"낮음", lowText:"자주 발생하는 작은 승리, 적당한 최대 배당금.",
    medLabel:"중간", medText:"더 적은 승리이지만 더 많은 적중에서 더 높은 배율.",
    highLabel:"높음", highText:"대부분의 조합은 0x를 지불하지만 모두 적중하면 최대 1,000x.",
    hitLabel:"히트", hitText:"슈에서 카드를 한 장 더 뽑습니다.",
    standLabel:"스탠드", standText:"현재 패를 유지하고 딜러가 플레이하게 합니다.",
    doubleLabel:"더블다운", doubleText:"베팅을 두 배로 늘리고 카드를 정확히 한 장 더 받은 후 스탠드.",
    splitLabel:"스플릿", splitText:"처음 두 장의 카드 값이 같으면 두 개의 독립된 패로 분리합니다.",
    insuranceLabel:"인슈어런스", insuranceText:"딜러가 에이스를 보여줄 때 딜러가 블랙잭이면 2:1을 지불하는 사이드 베팅을 할 수 있습니다.",
    fewerMinesLabel:"지뢰 적게", fewerMinesText:"공개당 작은 배율 증가, 낮은 위험.",
    moreMinesLabel:"지뢰 많게", moreMinesText:"큰 배율 점프, 하지만 지뢰에 닿을 가능성이 높음.",
    biggerGridLabel:"더 큰 그리드", biggerGridText:"더 많은 타일을 더 깊은 전략으로 탐색.",
    wildLabel:"와일드", wildText:"승리 조합을 완성하기 위해 일반 심볼을 대체합니다.",
    scatterLabel:"스캐터", scatterText:"릴에서의 위치에 관계없이 무료 스핀을 활성화합니다.",
    freeSpinsLabel:"무료 스핀", freeSpinsText:"모든 상품이 증가되는 무료 추가 라운드.",
    straightLabel:"스트레이트업", straightText:"특정 숫자에 베팅. 35:1 지불.",
    columnLabel:"열 (2:1)", columnText:"보드의 각 열 (12개 숫자). 2:1 지불.",
    dozenLabel:"다스 (2:1)", dozenText:"1-12, 13-24 또는 25-36. 2:1 지불.",
    evenMoneyLabel:"이븐 머니 (1:1)", evenMoneyText:"빨강/검정, 홀/짝, 낮음/높음. 1:1 지불.",
    playerLabel:"플레이어 (1:1)", playerText:"플레이어 패가 뱅커보다 높으면 두 배를 이깁니다.",
    bankerLabel:"뱅커 (0.95:1)", bankerText:"뱅커가 이기면 5% 수수료로 지불을 받습니다.",
    tieLabel:"타이 (8:1)", tieText:"두 패가 같은 값으로 끝나면 베팅의 8배를 이깁니다.",
  },
  nl: {
    lowRiskLabel:"Laag Risico", lowRiskText:"Vermenigvuldigers gelijkmatiger verdeeld. De meeste vallen keren terug dicht bij je inzet.",
    medRiskLabel:"Gemiddeld Risico", medRiskText:"Evenwichtige verdeling met gematigd hoge vermenigvuldigers en vaker kleine verliezen.",
    highRiskLabel:"Hoog Risico", highRiskText:"Extreme vermenigvuldigers aan de randen maar de meeste vallen keren 0x terug.",
    classicLabel:"Klassiek", classicText:"Evenwichtige uitbetalingen bij alle aantallen treffers.",
    lowLabel:"Laag", lowText:"Frequent kleine winsten, gematigde maximale uitbetalingen.",
    medLabel:"Gemiddeld", medText:"Minder winsten maar hogere vermenigvuldigers bij meer treffers.",
    highLabel:"Hoog", highText:"De meeste combinaties betalen 0x, maar alles raken betaalt tot 1.000x.",
    hitLabel:"Pak", hitText:"Trek nog een kaart.",
    standLabel:"Sta", standText:"Behoud je huidige hand en laat de dealer spelen.",
    doubleLabel:"Verdubbel", doubleText:"Verdubbel je inzet, neem precies één kaart meer, dan sta.",
    splitLabel:"Splits", splitText:"Als je eerste twee kaarten dezelfde waarde hebben, splits ze in twee aparte handen.",
    insuranceLabel:"Verzekering", insuranceText:"Wanneer de dealer een Aas toont, kun je een zijweddenschap plaatsen die 2:1 betaalt als de dealer Blackjack heeft.",
    fewerMinesLabel:"Minder mijnen", fewerMinesText:"Kleinere vermenigvuldigerstappen per onthulling, maar lager risico.",
    moreMinesLabel:"Meer mijnen", moreMinesText:"Grotere vermenigvuldigersprongen, maar grotere kans een mijn te raken.",
    biggerGridLabel:"Grotere roosters", biggerGridText:"Meer vakjes om te verkennen met grotere strategische diepte.",
    wildLabel:"Wild", wildText:"Vervangt elk normaal symbool om winnende combinaties te voltooien.",
    scatterLabel:"Scatter", scatterText:"Activeert gratis spins ongeacht positie op de rollen.",
    freeSpinsLabel:"Gratis Spins", freeSpinsText:"Extra rondes gratis waarbij alle prijzen worden vermenigvuldigd.",
    straightLabel:"Volledig (Plein)", straightText:"Wedden op een specifiek nummer. Betaalt 35:1.",
    columnLabel:"Kolom (2:1)", columnText:"Elke kolom van het bord (12 nummers). Betaalt 2:1.",
    dozenLabel:"Dozijn (2:1)", dozenText:"1-12, 13-24 of 25-36. Betaalt 2:1.",
    evenMoneyLabel:"Gelijkspel (1:1)", evenMoneyText:"Rood/Zwart, Even/Oneven, Laag/Hoog. Betaalt 1:1.",
    playerLabel:"Speler (1:1)", playerText:"Als de Spelerhand hoger is dan de Bankier, win je dubbel.",
    bankerLabel:"Bankier (0.95:1)", bankerText:"Als de Bankier wint, ontvang je je uitbetaling met 5% commissie.",
    tieLabel:"Gelijkspel (8:1)", tieText:"Als beide handen gelijk eindigen, win je 8x je inzet.",
  },
  pl: {
    lowRiskLabel:"Niskie Ryzyko", lowRiskText:"Mnożniki rozłożone bardziej równomiernie. Większość upadków zwraca bliski twojemu zakładowi.",
    medRiskLabel:"Średnie Ryzyko", medRiskText:"Zrównoważony rozkład z umiarkowanie wysokimi mnożnikami i częstszymi małymi stratami.",
    highRiskLabel:"Wysokie Ryzyko", highRiskText:"Ekstremalne mnożniki na krawędziach, ale większość upadków zwraca 0x.",
    classicLabel:"Klasyczny", classicText:"Zrównoważone wypłaty przy wszystkich liczbach trafień.",
    lowLabel:"Niski", lowText:"Częste małe wygrane, umiarkowane maksymalne wypłaty.",
    medLabel:"Średni", medText:"Mniej wygranych, ale wyższe mnożniki przy większej liczbie trafień.",
    highLabel:"Wysoki", highText:"Większość kombinacji płaci 0x, ale trafienie wszystkich płaci do 1000x.",
    hitLabel:"Dobierz", hitText:"Dobierz kolejną kartę z buta.",
    standLabel:"Stój", standText:"Zachowaj bieżącą rękę i pozwól krupierowi grać.",
    doubleLabel:"Podwój", doubleText:"Podwój swój zakład, dobierz dokładnie jedną kartę więcej, potem stój.",
    splitLabel:"Podziel", splitText:"Jeśli twoje pierwsze dwie karty mają tę samą wartość, podziel je na dwie osobne ręce.",
    insuranceLabel:"Ubezpieczenie", insuranceText:"Gdy krupier pokazuje As, możesz złożyć zakład boczny płacący 2:1 jeśli ma Blackjacka.",
    fewerMinesLabel:"Mniej min", fewerMinesText:"Mniejsze przyrosty mnożnika za odkrycie, ale mniejsze ryzyko.",
    moreMinesLabel:"Więcej min", moreMinesText:"Większe skoki mnożnika, ale większa szansa trafienia miny.",
    biggerGridLabel:"Większe siatki", biggerGridText:"Więcej pól do eksploracji z większą głębią strategiczną.",
    wildLabel:"Wild", wildText:"Zastępuje dowolny normalny symbol, aby uzupełnić zwycięskie kombinacje.",
    scatterLabel:"Scatter", scatterText:"Aktywuje darmowe spiny niezależnie od pozycji na bębnach.",
    freeSpinsLabel:"Darmowe Spiny", freeSpinsText:"Dodatkowe rundy bez kosztów, w których wszystkie nagrody są mnożone.",
    straightLabel:"Pełna (Plein)", straightText:"Zakład na konkretną liczbę. Płaci 35:1.",
    columnLabel:"Kolumna (2:1)", columnText:"Każda kolumna planszy (12 liczb). Płaci 2:1.",
    dozenLabel:"Tuzin (2:1)", dozenText:"1-12, 13-24 lub 25-36. Płaci 2:1.",
    evenMoneyLabel:"Pieniądz parzysty (1:1)", evenMoneyText:"Czerwone/Czarne, Parzyste/Nieparzyste, Niskie/Wysokie. Płaci 1:1.",
    playerLabel:"Gracz (1:1)", playerText:"Jeśli ręka Gracza jest wyższa niż Bankiera, wygrywasz podwójnie.",
    bankerLabel:"Bankier (0.95:1)", bankerText:"Jeśli Bankier wygrywa, otrzymujesz wypłatę z 5% prowizją.",
    tieLabel:"Remis (8:1)", tieText:"Jeśli obie ręce kończą się równo, wygrywasz 8x swój zakład.",
  },
  ru: {
    lowRiskLabel:"Низкий риск", lowRiskText:"Множители распределены более равномерно. Большинство падений возвращают близко к вашей ставке.",
    medRiskLabel:"Средний риск", medRiskText:"Сбалансированное распределение с умеренно высокими множителями и частыми небольшими потерями.",
    highRiskLabel:"Высокий риск", highRiskText:"Экстремальные множители по краям, но большинство падений возвращают 0x.",
    classicLabel:"Классический", classicText:"Сбалансированные выплаты при всех количествах совпадений.",
    lowLabel:"Низкий", lowText:"Частые маленькие выигрыши, умеренные максимальные выплаты.",
    medLabel:"Средний", medText:"Меньше выигрышей, но более высокие множители при большем количестве совпадений.",
    highLabel:"Высокий", highText:"Большинство комбинаций платят 0x, но попадание во все платит до 1000x.",
    hitLabel:"Взять", hitText:"Возьмите ещё одну карту.",
    standLabel:"Стоп", standText:"Сохраните текущую руку и дайте дилеру играть.",
    doubleLabel:"Удвоить", doubleText:"Удвойте ставку, возьмите ровно одну карту, затем стоп.",
    splitLabel:"Разделить", splitText:"Если ваши первые две карты имеют одинаковое значение, разделите их на две отдельные руки.",
    insuranceLabel:"Страховка", insuranceText:"Когда дилер показывает туз, можно сделать боковую ставку, которая платит 2:1 если у дилера блэкджек.",
    fewerMinesLabel:"Меньше мин", fewerMinesText:"Меньшие приращения множителя за открытие, но меньший риск.",
    moreMinesLabel:"Больше мин", moreMinesText:"Большие скачки множителя, но выше вероятность попасть на мину.",
    biggerGridLabel:"Большие сетки", biggerGridText:"Больше клеток для изучения с большей стратегической глубиной.",
    wildLabel:"Вайлд", wildText:"Заменяет любой обычный символ для завершения выигрышных комбинаций.",
    scatterLabel:"Скаттер", scatterText:"Активирует бесплатные вращения независимо от позиции на барабанах.",
    freeSpinsLabel:"Бесплатные вращения", freeSpinsText:"Дополнительные раунды бесплатно, где все призы умножаются.",
    straightLabel:"Прямо (Плейн)", straightText:"Ставка на конкретное число. Платит 35:1.",
    columnLabel:"Колонка (2:1)", columnText:"Каждая колонка доски (12 чисел). Платит 2:1.",
    dozenLabel:"Дюжина (2:1)", dozenText:"1-12, 13-24 или 25-36. Платит 2:1.",
    evenMoneyLabel:"Чёт/нечет (1:1)", evenMoneyText:"Красное/Чёрное, Чётное/Нечётное, Низкое/Высокое. Платит 1:1.",
    playerLabel:"Игрок (1:1)", playerText:"Если рука Игрока выше Банкира, вы выигрываете вдвое.",
    bankerLabel:"Банкир (0.95:1)", bankerText:"Если Банкир выигрывает, вы получаете выплату с комиссией 5%.",
    tieLabel:"Ничья (8:1)", tieText:"Если обе руки заканчиваются одинаково, вы выигрываете 8x вашу ставку.",
  },
  tr: {
    lowRiskLabel:"Düşük Risk", lowRiskText:"Çarpanlar daha eşit dağılmış. Düşüşlerin çoğu bahsinize yakın döner.",
    medRiskLabel:"Orta Risk", medRiskText:"Orta derecede yüksek çarpanlar ve daha sık küçük kayıplarla dengeli dağılım.",
    highRiskLabel:"Yüksek Risk", highRiskText:"Kenarlarda aşırı çarpanlar ama düşüşlerin çoğu 0x döner.",
    classicLabel:"Klasik", classicText:"Tüm isabetlerde dengeli ödemeler.",
    lowLabel:"Düşük", lowText:"Sık küçük kazanımlar, orta düzey maksimum ödemeler.",
    medLabel:"Orta", medText:"Daha az kazanım ama daha fazla eşleşmede daha yüksek çarpanlar.",
    highLabel:"Yüksek", highText:"Kombinasyonların çoğu 0x öder, ancak hepsini vurmak 1.000x'e kadar öder.",
    hitLabel:"Kart Al", hitText:"Desteden bir kart daha çekin.",
    standLabel:"Dur", standText:"Mevcut elinizi koruyun ve krupiyenin oynamasına izin verin.",
    doubleLabel:"İki Katla", doubleText:"Bahsinizi ikiye katlayın, tam olarak bir kart daha alın, sonra durun.",
    splitLabel:"Böl", splitText:"İlk iki kartınızın değeri aynıysa, onları iki ayrı ele bölün.",
    insuranceLabel:"Sigorta", insuranceText:"Krupiye As gösterdiğinde, krupiyenin Blackjack'i olması durumunda 2:1 ödeyen yan bahis yapabilirsiniz.",
    fewerMinesLabel:"Daha az mayın", fewerMinesText:"Açıklama başına daha küçük çarpan artışları, ancak daha düşük risk.",
    moreMinesLabel:"Daha fazla mayın", moreMinesText:"Daha büyük çarpan sıçramaları, ancak mayına çarpma olasılığı daha yüksek.",
    biggerGridLabel:"Daha büyük ızgaralar", biggerGridText:"Daha fazla stratejik derinlikle keşfedilecek daha fazla karo.",
    wildLabel:"Wild", wildText:"Kazanan kombinasyonları tamamlamak için herhangi bir normal sembolün yerine geçer.",
    scatterLabel:"Scatter", scatterText:"Makaralardaki konumundan bağımsız olarak ücretsiz döndürmeleri etkinleştirir.",
    freeSpinsLabel:"Ücretsiz Döndürmeler", freeSpinsText:"Tüm ödüllerin çarpıldığı ücretsiz ek turlar.",
    straightLabel:"Düz (Plein)", straightText:"Belirli bir sayıya bahis. 35:1 öder.",
    columnLabel:"Sütun (2:1)", columnText:"Tahtanın her sütunu (12 sayı). 2:1 öder.",
    dozenLabel:"Düzine (2:1)", dozenText:"1-12, 13-24 veya 25-36. 2:1 öder.",
    evenMoneyLabel:"Eşit Para (1:1)", evenMoneyText:"Kırmızı/Siyah, Çift/Tek, Düşük/Yüksek. 1:1 öder.",
    playerLabel:"Oyuncu (1:1)", playerText:"Oyuncu eli Bankir'den yüksekse, çift kazanırsınız.",
    bankerLabel:"Bankir (0.95:1)", bankerText:"Bankir kazanırsa, %5 komisyonla ödeme alırsınız.",
    tieLabel:"Beraberlik (8:1)", tieText:"Her iki el aynı değerle biterse, bahsinizin 8 katını kazanırsınız.",
  },
};

type BodyKey = string;
const BODY_TRANS: Record<string, Record<BodyKey,string>> = {
  es: {
    diceHowToPlay:    "Establece tu monto de apuesta y elige un número objetivo con el slider. Luego selecciona Roll Over o Roll Under. Se genera un número aleatorio provably fair. Si el resultado cae en tu lado elegido del objetivo, ganas.",
    diceWinProb:      "Tu probabilidad de ganar está determinada por tu objetivo. Por ejemplo, tirar por encima de 50 da ~49.99% con un pago de ~2x. Tirar por encima de 95 da ~4.99% con ~19.8x. El multiplicador se ajusta automáticamente al mover el slider.",
    dicePF:           "Cada tirada se determina combinando la semilla del servidor, tu semilla de cliente y un nonce. Después de cada apuesta puedes verificar que el resultado no fue manipulado. Puedes rotar tu semilla de cliente en cualquier momento.",
    plinkoHowToPlay:  "Establece tu monto de apuesta, elige un nivel de riesgo (Bajo, Medio o Alto) y selecciona el número de filas (8 a 16). Presiona Apostar para soltar una bola. La bola rebota aleatoriamente y aterriza en un slot multiplicador. Tu pago es tu apuesta multiplicada por el valor del slot.",
    plinkoPF:         "Cada caída de bola se determina combinando la semilla del servidor, tu semilla de cliente y un nonce. El hash resultante determina la dirección en cada clavija. Puedes rotar tu semilla de cliente en cualquier momento.",
    kenoHowToPlay:    "Establece tu monto de apuesta y selecciona entre 1 y 10 números. Elige un nivel de riesgo (Clásico, Bajo, Medio o Alto), luego presiona Apostar. El juego sortea 10 números. Tu pago depende de cuántos picks coincidan con los números sorteados.",
    kenoPF:           "Los 10 números sorteados se determinan combinando la semilla del servidor, tu semilla de cliente y un nonce. Cada sorteo es independientemente verificable. Puedes rotar tu semilla de cliente en cualquier momento.",
    bjHowToPlay:      "Establece tu monto de apuesta y presiona Repartir. Tu objetivo es acercarte lo más posible a 21 sin pasarte. Las figuras cuentan como 10, los Ases como 1 u 11.",
    bjPayouts:        "Una victoria estándar paga 1:1. Un Blackjack natural paga 3:2. Si empatas con el crupier, es un empate y se devuelve tu apuesta. El crupier debe pedir con 16 y plantarse con 17.",
    bjPF:             "Antes de cada mano, semilla del servidor, tu semilla de cliente y un nonce se combinan para mezclar un zapato de 312 cartas. Puedes verificar la mezcla y rotar tu semilla en cualquier momento.",
    minesHowToPlay:   "Establece tu monto de apuesta y elige un tamaño de cuadrícula. Selecciona el número de minas. Presiona 'Iniciar Juego', luego haz clic en las casillas para revelarlas. Cada casilla segura muestra una gema. Presiona 'Cobrar' en cualquier momento.",
    minesPF:          "Las posiciones de las minas se determinan antes de que comience el juego usando la semilla del servidor, tu semilla de cliente y un nonce. Cada juego es independientemente verificable.",
    slotHowToPlay:    "Establece tu monto de apuesta y presiona Girar. Los carretes se detienen aleatoriamente en una combinación de símbolos. Las combinaciones ganadoras siguen las líneas de pago definidas.",
    slotPayouts:      "Cada símbolo tiene un valor de pago diferente. Consulta la tabla de pagos dentro del juego para ver los multiplicadores exactos.",
    hiloHowToPlay:    "Establece tu apuesta y pulsa 'Nuevo Juego'. Luego elige MAYOR si crees que la siguiente carta tendrá un valor más alto, o MENOR si crees que será más baja. Encadena aciertos para multiplicar tus ganancias.",
    hiloDynMult:      "Los multiplicadores se calculan en tiempo real según la probabilidad de cada carta. Para un 2, MAYOR tiene un multiplicador bajo (~1.07x) porque es probable ganar, mientras que MENOR tiene uno alto (~6.44x). RTP del 99%.",
    hiloCashOut:      "Después de cada acierto puedes presionar 'Retirar' para cobrar tus ganancias acumuladas, o seguir apostando para multiplicar aún más. Si fallas, pierdes tu apuesta inicial.",
    hiloPF:           "Cada carta revelada se extrae de una baraja mezclada usando la semilla del servidor, tu semilla de cliente y un nonce. El orden completo queda determinado antes de comenzar la mano. Puedes rotar tu semilla en cualquier momento.",
    rouletteHowToPlay:"Selecciona el valor de tu ficha y haz clic en los números, columnas, docenas o apuestas externas. Puedes colocar varias fichas antes de girar. Pulsa 'Apostar' para lanzar la rueda. La bola cae en uno de los 37 números (0-36).",
    rouletteAutoMode: "Activa el modo Automático para lanzar la rueda repetidamente. Establece un número fijo de giros o usa ∞ para juego continuo. Pulsa 'Detener Auto' en cualquier momento.",
    roulettePF:       "Cada giro genera un número entre 0 y 36 combinando la semilla del servidor, tu semilla de cliente y un nonce de forma criptográficamente segura. El resultado es verificable de forma independiente.",
    baccaratHowToPlay:"Selecciona el valor de tu ficha y haz clic en la zona de apuesta: Jugador, Banca o Empate. Podés apostar en varias zonas. Presioná 'Repartir'. Se reparten dos cartas a cada lado; se aplican las reglas de tercera carta estándar.",
    baccaratCardVals: "Los Ases valen 1. Las figuras (J, Q, K) y los 10 valen 0. Todas las demás cartas valen su número. El total es la suma módulo 10.",
    baccaratThirdCard:"El Jugador recibe tercera carta si su total es 0-5. La Banca sigue sus propias reglas que dependen de su total y la tercera carta del Jugador. Ambos se plantan con 8 o 9 (natural).",
    baccaratAutoMode: "Activá el modo Auto para jugar rondas consecutivas automáticamente. Podés configurar la cantidad de rondas o usar ∞. Presioná 'Detener Auto' en cualquier momento.",
    baccaratPF:       "El mazo de 8 barajas se mezcla usando la semilla del servidor, tu semilla de cliente y un nonce antes de cada zapato. El orden completo queda determinado criptográficamente. Se genera un nuevo mazo cuando quedan menos de 15 cartas.",
  },
  en: {
    diceHowToPlay:    "Set your bet amount and choose a target number with the slider. Then select Roll Over or Roll Under. A provably fair random number is generated. If the result lands on your chosen side of the target, you win.",
    diceWinProb:      "Your win probability is determined by your target. For example, rolling over 50 gives ~49.99% chance with ~2x payout. Rolling over 95 gives ~4.99% chance with ~19.8x. The multiplier adjusts automatically as you move the slider.",
    dicePF:           "Each roll is determined by combining the server seed, your client seed, and a nonce. After each bet you can verify the result was not manipulated. You can rotate your client seed at any time.",
    plinkoHowToPlay:  "Set your bet amount, choose a risk level (Low, Medium, or High) and select the number of rows (8 to 16). Press Bet to drop a ball. The ball bounces randomly and lands in a multiplier slot. Your payout is your bet multiplied by the slot value.",
    plinkoPF:         "Each ball drop is determined by combining the server seed, your client seed, and a nonce. The resulting hash determines direction at each peg. You can rotate your client seed at any time.",
    kenoHowToPlay:    "Set your bet amount and select 1 to 10 numbers. Choose a risk level (Classic, Low, Medium, or High), then press Bet. The game draws 10 numbers. Your payout depends on how many of your picks match.",
    kenoPF:           "The 10 drawn numbers are determined by combining the server seed, your client seed, and a nonce. Each draw is independently verifiable. You can rotate your client seed at any time.",
    bjHowToPlay:      "Set your bet amount and press Deal. Your goal is to get as close to 21 as possible without going over. Face cards count as 10, Aces count as 1 or 11.",
    bjPayouts:        "A standard win pays 1:1. A natural Blackjack pays 3:2. If you tie with the dealer, it's a push and your bet is returned. The dealer must hit on 16 and stand on 17.",
    bjPF:             "Before each hand, the server seed, client seed, and nonce are combined to deterministically shuffle a 312-card shoe. You can verify the shuffle and rotate your seed at any time.",
    minesHowToPlay:   "Set your bet amount and choose a grid size. Select the number of mines. Press 'Start Game', then click tiles to reveal them. Each safe tile shows a gem. Press 'Cash Out' at any time.",
    minesPF:          "Mine positions are determined before the game starts using the server seed, client seed, and a nonce. Every game is independently verifiable.",
    slotHowToPlay:    "Set your bet amount and press Spin. The reels stop randomly on a combination of symbols. Winning combinations follow the defined paylines.",
    slotPayouts:      "Each symbol has a different payout value. Check the in-game paytable for exact multipliers.",
    hiloHowToPlay:    "Set your bet and press 'New Game' to receive your first card. Then choose HIGHER if you think the next card will be of higher (or equal) value, or LOWER if you think it'll be lower. Chain correct guesses to multiply your winnings.",
    hiloDynMult:      "Multipliers are calculated in real-time based on each card's probability. For a low card like 2, HIGHER has a low multiplier (~1.07x) because it's likely to win, while LOWER has a high one (~6.44x). The game uses 99% RTP.",
    hiloCashOut:      "After each correct guess you can press 'Cash Out' to collect your accumulated winnings, or keep betting to multiply further. If you're wrong at any point, you lose your initial bet.",
    hiloPF:           "Each revealed card is drawn from a shuffled deck using the server seed, client seed, and a nonce. The full deck order is determined before the hand begins and can be independently verified after the game. You can rotate your client seed at any time.",
    rouletteHowToPlay:"Select your chip value and click on numbers, columns, dozens, or outside bets to place chips. You can place multiple chips before spinning. Press 'Bet' to launch the wheel. The ball falls randomly on one of 37 numbers (0-36).",
    rouletteAutoMode: "Enable Auto Mode to spin the wheel repeatedly using the same chip layout. Set a fixed number of spins or use ∞ for continuous play. Press 'Stop Auto' at any time.",
    roulettePF:       "Each spin generates a number between 0 and 36 by combining the server seed, client seed, and nonce cryptographically. The result is independently verifiable.",
    baccaratHowToPlay:"Select your chip value and click a betting zone: Player, Banker, or Tie. You can bet on multiple zones. Press 'Deal'. Two cards are dealt to each side; standard Baccarat third-card rules apply.",
    baccaratCardVals: "Aces are worth 1. Face cards (J, Q, K) and 10s are worth 0. All other cards are worth their face value. The total is the sum modulo 10.",
    baccaratThirdCard:"The Player draws a third card if their total is 0-5. The Banker follows their own rules depending on their total and the Player's third card. Both stand on 8 or 9 (natural).",
    baccaratAutoMode: "Enable Auto Mode to play consecutive rounds automatically. You can configure the number of rounds or use ∞. Press 'Stop Auto' at any time.",
    baccaratPF:       "The 8-deck shoe is shuffled using the server seed, client seed, and a nonce before each shoe. The full deck order is determined cryptographically. A new verifiable shoe is generated when fewer than 15 cards remain.",
  },
  pt: {
    diceHowToPlay:    "Defina o valor da aposta e escolha um número alvo com o slider. Em seguida, selecione Roll Over ou Roll Under. Um número aleatório provably fair é gerado. Se o resultado cair do seu lado escolhido do alvo, você ganha.",
    diceWinProb:      "Sua probabilidade de vitória é determinada pelo seu alvo. Por exemplo, rolar acima de 50 dá ~49,99% com pagamento de ~2x. Rolar acima de 95 dá ~4,99% com ~19,8x. O multiplicador se ajusta automaticamente.",
    dicePF:           "Cada lançamento é determinado combinando a semente do servidor, sua semente de cliente e um nonce. Após cada aposta, você pode verificar que o resultado não foi manipulado.",
    plinkoHowToPlay:  "Defina o valor da aposta, escolha um nível de risco (Baixo, Médio ou Alto) e selecione o número de fileiras (8 a 16). Pressione Apostar para soltar uma bola. A bola quica aleatoriamente e cai em um slot multiplicador.",
    plinkoPF:         "Cada queda de bola é determinada combinando a semente do servidor, sua semente de cliente e um nonce. O hash resultante determina a direção em cada pino.",
    kenoHowToPlay:    "Defina o valor da aposta e selecione de 1 a 10 números. Escolha um nível de risco (Clássico, Baixo, Médio ou Alto), depois pressione Apostar. O jogo sorteia 10 números.",
    kenoPF:           "Os 10 números sorteados são determinados combinando a semente do servidor, sua semente de cliente e um nonce. Cada sorteio é independentemente verificável.",
    bjHowToPlay:      "Defina o valor da aposta e pressione Distribuir. Seu objetivo é chegar o mais próximo possível de 21 sem ultrapassar. Figuras valem 10, Ases valem 1 ou 11.",
    bjPayouts:        "Uma vitória padrão paga 1:1. Um Blackjack natural paga 3:2. Empate com o dealer devolve a aposta. O dealer deve pedir no 16 e parar no 17.",
    bjPF:             "Antes de cada mão, semente do servidor, semente do cliente e nonce são combinados para embaralhar o sapato de 312 cartas deterministicamente. Você pode verificar e rotacionar sua semente a qualquer momento.",
    minesHowToPlay:   "Defina o valor da aposta e escolha um tamanho de grade. Selecione o número de minas. Pressione 'Iniciar', depois clique nas casas para revelá-las. Cada casa segura mostra uma gema. Pressione 'Retirar' quando quiser.",
    minesPF:          "As posições das minas são determinadas antes do início do jogo usando a semente do servidor, semente do cliente e um nonce. Cada jogo é verificável de forma independente.",
    slotHowToPlay:    "Defina o valor da aposta e pressione Girar. Os rolos param aleatoriamente em uma combinação de símbolos. Combinações vencedoras seguem as linhas de pagamento definidas.",
    slotPayouts:      "Cada símbolo tem um valor de pagamento diferente. Consulte a tabela de pagamentos no jogo para ver os multiplicadores exatos.",
    hiloHowToPlay:    "Defina sua aposta e pressione 'Novo Jogo'. Escolha MAIS ALTO se achar que a próxima carta terá valor maior, ou MAIS BAIXO se achar que será menor. Encadeie acertos para multiplicar seus ganhos.",
    hiloDynMult:      "Os multiplicadores são calculados em tempo real com base na probabilidade de cada carta. Para um 2, MAIS ALTO tem multiplicador baixo (~1,07x) pois é provável ganhar, enquanto MAIS BAIXO tem um alto (~6,44x). RTP de 99%.",
    hiloCashOut:      "Após cada acerto, pressione 'Sacar' para cobrar seus ganhos acumulados ou continue apostando. Se errar, perde a aposta inicial.",
    hiloPF:           "Cada carta revelada é retirada de um baralho embaralhado usando semente do servidor, semente do cliente e nonce. A ordem completa é determinada antes de começar a mão.",
    rouletteHowToPlay:"Selecione o valor da ficha e clique em números, colunas, dúzias ou apostas externas. Pode colocar várias fichas antes de girar. Pressione 'Apostar' para lançar a roda. A bola cai em um dos 37 números (0-36).",
    rouletteAutoMode: "Ative o modo Automático para lançar a roda repetidamente. Defina um número fixo de giros ou use ∞. Pressione 'Parar Auto' a qualquer momento.",
    roulettePF:       "Cada giro gera um número entre 0 e 36 combinando semente do servidor, semente do cliente e nonce de forma criptograficamente segura.",
    baccaratHowToPlay:"Selecione o valor da ficha e clique em uma zona de aposta: Jogador, Banco ou Empate. Pressione 'Distribuir'. Duas cartas são dadas a cada lado; as regras padrão de terceira carta do Bacará se aplicam.",
    baccaratCardVals: "Ases valem 1. Figuras (J, Q, K) e 10s valem 0. Todas as outras cartas valem seu número. O total é a soma módulo 10.",
    baccaratThirdCard:"O Jogador recebe terceira carta se seu total for 0-5. O Banco segue suas próprias regras dependendo do total e da terceira carta do Jogador. Ambos param com 8 ou 9 (natural).",
    baccaratAutoMode: "Ative o modo Auto para jogar rodadas consecutivas automaticamente. Configure o número de rodadas ou use ∞. Pressione 'Parar Auto' a qualquer momento.",
    baccaratPF:       "O baralho de 8 cartas é embaralhado usando semente do servidor, semente do cliente e nonce antes de cada sapato. A ordem completa é determinada criptograficamente.",
  },
};

const PF_BODY_FALLBACK = BODY_TRANS.en;

function B(lang: string, key: BodyKey): string {
  return BODY_TRANS[lang]?.[key] ?? BODY_TRANS.en?.[key] ?? key;
}

function BL(lang: string, key: BulletKey): string {
  return BULLET_TRANS[lang]?.[key] ?? BULLET_TRANS.en?.[key] ?? key;
}

function S(lang: string, key: SectionKey): string {
  return SECTION_TRANS[lang]?.[key] ?? SECTION_TRANS.en?.[key] ?? key;
}

export function getGameMeta(lang: Lang): Record<string, GameMeta> {
  const L = (META_TRANS as any)[lang] ?? META_TRANS.es;
  const result: Record<string, GameMeta> = {};
  for (const [game, bs] of Object.entries(BGSMAP)) {
    const t = L[game] ?? META_TRANS.es[game as GameKey];
    result[game] = { ...bs, title: t.title ?? game, desc: t.desc, sub: t.sub };
  }
  return result;
}

export function getGameInfo(lang: Lang): Record<string, GameInfoSection[]> {
  return {
    dice: [
      { heading: S(lang,"howToPlay"),   icon:"📖", body: B(lang,"diceHowToPlay") },
      { heading: S(lang,"winProb"),     icon:"💰", body: B(lang,"diceWinProb") },
      { heading: S(lang,"provablyFair"),icon:"🔒", body: B(lang,"dicePF") },
    ],
    plinko: [
      { heading: S(lang,"howToPlay"),   icon:"📖", body: B(lang,"plinkoHowToPlay") },
      { heading: S(lang,"riskLevels"),  icon:"📊", bullets:[
        { label: BL(lang,"lowRiskLabel"),  text: BL(lang,"lowRiskText") },
        { label: BL(lang,"medRiskLabel"),  text: BL(lang,"medRiskText") },
        { label: BL(lang,"highRiskLabel"), text: BL(lang,"highRiskText") },
      ]},
      { heading: S(lang,"provablyFair"),icon:"🔒", body: B(lang,"plinkoPF") },
    ],
    keno: [
      { heading: S(lang,"howToPlay"),   icon:"📖", body: B(lang,"kenoHowToPlay") },
      { heading: S(lang,"riskPayouts"), icon:"📊", bullets:[
        { label: BL(lang,"classicLabel"), text: BL(lang,"classicText") },
        { label: BL(lang,"lowLabel"),     text: BL(lang,"lowText") },
        { label: BL(lang,"medLabel"),     text: BL(lang,"medText") },
        { label: BL(lang,"highLabel"),    text: BL(lang,"highText") },
      ]},
      { heading: S(lang,"provablyFair"),icon:"🔒", body: B(lang,"kenoPF") },
    ],
    blackjack: [
      { heading: S(lang,"howToPlay"),   icon:"📖", body: B(lang,"bjHowToPlay") },
      { heading: S(lang,"yourOptions"), icon:"🎮", bullets:[
        { label: BL(lang,"hitLabel"),      text: BL(lang,"hitText") },
        { label: BL(lang,"standLabel"),    text: BL(lang,"standText") },
        { label: BL(lang,"doubleLabel"),   text: BL(lang,"doubleText") },
        { label: BL(lang,"splitLabel"),    text: BL(lang,"splitText") },
        { label: BL(lang,"insuranceLabel"),text: BL(lang,"insuranceText") },
      ]},
      { heading: S(lang,"payouts"),     icon:"💰", body: B(lang,"bjPayouts") },
      { heading: S(lang,"provablyFair"),icon:"🔒", body: B(lang,"bjPF") },
    ],
    mines: [
      { heading: S(lang,"howToPlay"),   icon:"📖", body: B(lang,"minesHowToPlay") },
      { heading: S(lang,"multRisk"),    icon:"📊", bullets:[
        { label: BL(lang,"fewerMinesLabel"), text: BL(lang,"fewerMinesText") },
        { label: BL(lang,"moreMinesLabel"),  text: BL(lang,"moreMinesText") },
        { label: BL(lang,"biggerGridLabel"), text: BL(lang,"biggerGridText") },
      ]},
      { heading: S(lang,"provablyFair"),icon:"🔒", body: B(lang,"minesPF") },
    ],
    slot: [
      { heading: S(lang,"howToPlay"),      icon:"📖", body: B(lang,"slotHowToPlay") },
      { heading: S(lang,"specialFeatures"),icon:"⭐", bullets:[
        { label: BL(lang,"wildLabel"),      text: BL(lang,"wildText") },
        { label: BL(lang,"scatterLabel"),   text: BL(lang,"scatterText") },
        { label: BL(lang,"freeSpinsLabel"), text: BL(lang,"freeSpinsText") },
      ]},
      { heading: S(lang,"payouts"),        icon:"💰", body: B(lang,"slotPayouts") },
    ],
    hilo: [
      { heading: S(lang,"howToPlay"),     icon:"📖", body: B(lang,"hiloHowToPlay") },
      { heading: S(lang,"dynamicMult"),   icon:"📊", body: B(lang,"hiloDynMult") },
      { heading: S(lang,"cashOrContinue"),icon:"💰", body: B(lang,"hiloCashOut") },
      { heading: S(lang,"provablyFair"),  icon:"🔒", body: B(lang,"hiloPF") },
    ],
    roulette: [
      { heading: S(lang,"howToPlay"), icon:"📖", body: B(lang,"rouletteHowToPlay") },
      { heading: S(lang,"betTypes"),  icon:"💰", bullets:[
        { label: BL(lang,"straightLabel"),   text: BL(lang,"straightText") },
        { label: BL(lang,"columnLabel"),     text: BL(lang,"columnText") },
        { label: BL(lang,"dozenLabel"),      text: BL(lang,"dozenText") },
        { label: BL(lang,"evenMoneyLabel"),  text: BL(lang,"evenMoneyText") },
      ]},
      { heading: S(lang,"autoMode"),      icon:"🎮", body: B(lang,"rouletteAutoMode") },
      { heading: S(lang,"provablyFair"),  icon:"🔒", body: B(lang,"roulettePF") },
    ],
    baccarat: [
      { heading: S(lang,"howToPlay"),  icon:"📖", body: B(lang,"baccaratHowToPlay") },
      { heading: S(lang,"betTypes"),   icon:"💰", bullets:[
        { label: BL(lang,"playerLabel"), text: BL(lang,"playerText") },
        { label: BL(lang,"bankerLabel"), text: BL(lang,"bankerText") },
        { label: BL(lang,"tieLabel"),    text: BL(lang,"tieText") },
      ]},
      { heading: S(lang,"cardValues"), icon:"ℹ️", body: B(lang,"baccaratCardVals") },
      { heading: S(lang,"thirdCard"),  icon:"ℹ️", body: B(lang,"baccaratThirdCard") },
      { heading: S(lang,"autoMode"),   icon:"🎮", body: B(lang,"baccaratAutoMode") },
      { heading: S(lang,"provablyFair"),icon:"🔒", body: B(lang,"baccaratPF") },
    ],
  };
}

export function getLearnMoreLabel(lang: Lang): string {
  return SECTION_TRANS[lang]?.learnMore ?? SECTION_TRANS.en.learnMore;
}
